<a class="button medium" href="<?php echo $this->url(array('controller' => 'Periodo', 'action' => 'bloque','id' => $this->id), null, TRUE); ?>"><i class="icon-hand-left"></i> Volver</a>
<?php if ($this->messages) : ?>
    <div class="t_a_message">
        <ul>
            <?php foreach ($this->messages as $msg) : ?>
                <li><?php echo $msg; ?></li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>



<?php echo $this->form ?>

<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js"></script>


<script>
    $('#tiempoInicio').timepicker({
        change: function(time) {
            var theAdd = new Date();
            var timestart=$("#tiempoInicio").val();
            var timeend='';

            arr = timestart.split(':');
            hour = $.trim(arr[0]);
            min = $.trim(arr[1]);
            console.log(min);


            // Set Hours, minutes, secons and miliseconds
            theAdd.setHours(hour, min, '00', '000');

            theAdd.setMinutes(theAdd.getMinutes() + 45);

            console.log(theAdd.getMinutes());

            if(theAdd.getMinutes().toString().length==1){
                timeend=theAdd.getHours() + ":0" + theAdd.getMinutes();
            }else{
                timeend=theAdd.getHours() + ":" + theAdd.getMinutes();
            }



            $("#tiempoTermino").val(timeend);
        },
        timeFormat: 'HH:mm ',
        interval: 5,
        minTime: '7',
        maxTime: '20:00',
        defaultTime: '8',
        startTime: '07:30',
        dynamic: false,
        dropdown: true,
        scrollbar: true
    });


</script>
