<a class="button medium grey"
   href="<?php echo $this->url(array(
       'controller' => 'Periodo',
       'action' => 'calendario'),
       null,
       true);
   ?>"><i class="icon-hand-left"></i> Volver</a>

<a class="button medium blue"
   href="<?php echo $this->url(array(
       'controller' => 'Periodo',
       'action' => 'agregarcalendariocurso'));
   ?>"><i class="icon-file"></i> Nuevo</a>

<div style="overflow-x:auto;">
    <table class="striped sortable" style="margin-top: 10px">
        <thead>
        <tr>
            <th>Curso</th>
            <th>Código Calendario</th>
            <th>Descripción Calendario</th>
            <th>Eventos</th>
        </tr>
        </thead>
        <?php foreach ($this->dato as $d) : ?>

            <tr>
                <td><?php echo $d->nombreGrado . " " . $d->letra ?></td>

                <td><?php echo (empty($d->codigoCalendario)) ? "Sin Calendario" : $d->codigoCalendario ?></td>

                <td><?php echo (empty($d->descripcionCalendario)) ? "No Creado" : $d->descripcionCalendario ?></td>

                <td>
                    <a class="button small blue"
                       href="<?php echo $this->url(array(
                           'controller' => 'Periodo',
                           'action' => 'eventocurso',
                           'id' => $d->idCalendario,
                           'idcu' => $d->idCursos,
                           'idc' => $this->idCalendarioEstablecimiento));
                       ?>"> Eventos</a>
                </td>


            </tr>

        <?php endforeach; ?>

    </table>
</div>
