<!--creo link para agregar un Periodo -->
<a class="button medium blue" href="<?php echo $this->url(array('controller' => 'Periodo', 'action' => 'agregarcalendario')); ?>">Crear Calendario</a>



<table class="striped sortable" style="margin-top: 10px">
    <thead>
    <tr>
        <th>Establecimiento</th>
        <th>Código Calendario</th>
        <th>Descripción Calendario</th>
        <th>Crear Evento</th>
        <th>Crear Crisis</th>
        <th>Editar</th>
        <th>Eliminar</th>

    </tr>
    </thead>
    <?php foreach ($this->dato as $d) : ?>

        <tr>
            <td><?php echo $d->nombreEstablecimiento ?></td>

            <td><?php echo (empty($d->codigoCalendario))? "Sin Calendario": $d->codigoCalendario ?></td>

            <td><?php echo (empty($d->descripcionCalendario))? "No Creado": $d->descripcionCalendario ?></td>

            <td><a class="button small blue" href="<?php echo $this->url(array('controller' => 'Periodo',
                    'action' => 'agregarevento', 'id' => $d->idCalendarioEstablecimiento)); ?>">Agregar Evento</a></td>

            <td><a class="button small orange" href="<?php echo $this->url(array('controller' => 'Periodo',
                    'action' => 'agregarcrisis', 'id' => $d->idCalendarioEstablecimiento)); ?>">Agregar Crisis</a></td>

            <td><a class="button small green" href="<?php echo $this->url(array('controller' => 'Periodo',
                    'action' => 'editarcalendario', 'id' => $d->idCalendarioEstablecimiento)); ?>">Editar</a></td>

            <td><a class="button small red" href="<?php echo $this->url(array('controller' => 'Periodo',
                    'action' => 'eliminarcalendario', 'id' => $d->idCalendarioEstablecimiento)); ?>">Eliminar</a></td>

        </tr>

    <?php endforeach; ?>

</table>
