<a class="button medium" href="<?php echo $this->url(array('controller' => 'Periodo', 'action' => 'bloque','id' => $this->id), null, TRUE); ?>"><i class="icon-hand-left"></i> Volver</a>
<?php if ($this->messages) : ?>
    <div class="t_a_message">
        <ul>
            <?php foreach ($this->messages as $msg) : ?>
                <li><?php echo $msg; ?></li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>



<?php echo $this->form ?>

<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js"></script>

