<style>

    .alert {
        position: relative;
        padding: 0.75rem 1.25rem;
        margin-bottom: 1rem;
        border: 1px solid transparent;
        border-radius: 0.25rem;
    }
    .alert-danger {
        color: #721c24;
        background-color: #f8d7da;
        border-color: #f5c6cb;
    }

    .alert-danger hr {
        border-top-color: #f1b0b7;
    }

    .alert-danger .alert-link {
        color: #491217;
    }
</style>
<a class="button medium" href="<?php echo $this->url(array('controller' => 'Periodo','action' => 'bloque','id'=>$this->dato), null, TRUE); ?>"><i class="icon-hand-left"></i> Volver</a>
<?php if ($this->messages) : ?>
    <div class="alert alert-danger">

        <?php foreach ($this->messages as $msg) : ?>
            <h5 class="center"><?php echo $msg; ?></h5>
        <?php endforeach; ?>

    </div>
<?php endif; ?>
