<script src="<?php echo $this->baseUrl; ?>/javascript/jquery.twosidedmultiselect.js"></script>
<script src="<?php echo $this->baseUrl; ?>/javascript/buscador.js"></script>
<script src="<?php echo $this->baseUrl; ?>/javascript/alumnosorden.js"></script>

<style>
    #divInfo {
        text-align: center;
        padding-bottom: 10px;
        margin-bottom: 40px;
    }


    input[type="text"] {
        padding: 5px;
        width: 595px;
    }
</style>

<?php
$nombrecurso = new Zend_Session_Namespace('nombre_curso');
$nombre_curso = $nombrecurso->nombre_curso;

$monitoreos = new Zend_Session_Namespace('monitoreo');
$monitoreo = $monitoreos->monitoreo;

$establecimientos = new Zend_Session_Namespace('idesta');
$id_establecimiento = $establecimientos->idesta;


if ($this->messages) {
    ?>
    <div class="error">
        <p>
            <?php foreach ($this->messages as $msg): ?>
                <?php echo $msg; ?>
            <?php endforeach; ?>


        </p>

    </div>
    <a class="button medium blue" href="<?php echo $this->url(array('controller' => 'Libro',
        'action' => 'index'), null, true);
    ?>"><i class="icon-hand-left"></i> Volver</a>
<?php } else {
$roles = new Zend_Session_Namespace('cargo');
$rol = $roles->cargo;

$codigos = new Zend_Session_Namespace('codigo');
$codigo = $codigos->codigo;

?>


<a class="button medium grey" href="<?php echo $this->url(array('controller' => 'Libro',
    'action' => 'index'), null, true);
?>"><i class="icon-hand-left"></i> Volver</a>


<?php if ($codigo == 10) { ?>

    <a class="button medium blue" href="<?php echo $this->url(array('controller' => 'Libro',
        'action' => 'notasnuevopre'), null, true);
    ?>"><i class="icon-hand-up"></i> Notas </a>
<?php } else {
    if ($monitoreo == 1 && $id_establecimiento != 8) { ?>
        <a class="button medium blue" href="<?php echo $this->url(array('controller' => 'Libro',
            'action' => 'notasnuevo'), null, true);
        ?>"><i class="icon-hand-up"></i> Notas </a>

    <?php } elseif ($monitoreo == 0) { ?>

        <a class="button medium blue" href="<?php echo $this->url(array('controller' => 'Libro',
            'action' => 'notasnuevo'), null, true);
        ?>"><i class="icon-hand-up"></i> Notas </a>

    <?php }?>

    <a class="button medium blue" href="<?php echo $this->url(array('controller' => 'Libro',
        'action' => 'controlasistencias'), null, true);
    ?>"><i class="icon-hand-up"></i> Control de Asistencia</a>

    <a class="button medium blue" href="<?php echo $this->url(array('controller' => 'Libro',
        'action' => 'controlregistros'), null, true);
    ?>"><i class="icon-hand-up"></i> Control Clases </a>



<?php }

if ($rol == '1' || $rol == '3' || $rol == '6') { ?>

    <a class="button medium blue" href="<?php echo $this->url(array('controller' => 'Libro',
        'action' => 'observaciones'), null, true);
    ?>"><i class="icon-hand-up"></i> Observaciones</a>


    <?php if ($monitoreo == 1) { ?>

        <a class="button medium blue" href="<?php echo $this->url(array('controller' => 'Libro',
            'action' => 'monitoreo'), null, true);
        ?>"><i class="icon-hand-up"></i> Monitoreo Evaluación </a>
    <?php } ?>


<?php } ?>


<?php if ($rol == '2') { ?>

    <a class="button medium blue" href="<?php echo $this->url(array('controller' => 'Libro',
        'action' => 'observaciones'), null, true);
    ?>"><i class="icon-hand-up"></i> Observaciones</a>

    <?php if ($monitoreo == 1) { ?>

        <a class="button medium blue" href="<?php echo $this->url(array('controller' => 'Libro',
            'action' => 'monitoreo'), null, true);
        ?>"><i class="icon-hand-up"></i> Monitoreo Evaluación </a>
    <?php } ?>

<?php } ?>

<h4>Curso:
    <?php echo $nombre_curso; ?>

</h4>
<div style="overflow-x:auto;">

    <div id="divTabla" style="margin-top: 20px;">
                        <label for="txtBuscar">Buscar: </label>
                        <input type="text" id="txtBuscar" autofocus
                               placeholder="Escriba el texto que desea encontrar y presione ENTER">
        <!--creo una tabla para mostrar los datos-->
        <table id="tblTabla" class="striped sortable" style="margin-top: 10px">
            <thead>
            <tr>
                <th>Nº Lista</th>
                <th>Estudiante</th>
            </tr>
            </thead>
            <tbody>


            <?php
            if (!empty($this->datosalumnos)) {

            $r = 1;
            foreach ($this->datosalumnos as $d): ?>

                <tr>
                    <td><input type="hidden" class="ides" value="<?php echo $d['idAlumnosActual']; ?>"/><?php echo $r; ?></td>

                    <td><span style="word-spacing: 10px;"><?php echo $d['apaterno'].' '.$d['amaterno'].' '; ?></span><span><?php echo $d['nombres']; ?></span></td>
                </tr>


                <?php $r++;endforeach; ?>
            </tbody>
        </table>
        <?php


        if ($this->jefe == '1') {

            echo '<a id="guardaorden" class="button medium blue">Actualizar Orden</a>'; ?>
            <script>
                $('tbody').sortable();
            </script>
        <?php } ?>

        <?php } ?>


        <?php } ?>
    </div>
