<script src="<?php echo $this->baseUrl; ?>/javascript/buscador.js"></script>


<style>
    #divInfo {
        text-align: center;
        padding-bottom: 10px;
        margin-bottom: 40px;
    }

    #divTabla {

    }

    input[type="text"] {
        padding: 5px;
        width: 595px;
    }

    .center-header {
        display: -webkit-box;
        margin-top: 10px;
    }

    .center-header h4 {
        text-align: left;
    }
</style>
<?php
$nombrecurso = new Zend_Session_Namespace('nombre_curso');
$nombre_curso = $nombrecurso->nombre_curso;

$idcurso = new Zend_Session_Namespace('id_curso');
$id_curso = $idcurso->id_curso;

$iddetallecurso = new Zend_Session_Namespace('id_detalle_curso');
$id_detalle_curso = $iddetallecurso->id_detalle_curso;

$cargo = new Zend_Session_NameSpace("cargo");

$ingreson = new Zend_Session_Namespace('ingresonota');
$ingresonota = $ingreson->ingresonota;

$codigos = new Zend_Session_Namespace('codigo');
$codigo = $codigos->codigo;

if ($cargo->cargo == '2') { ?>

    <?php
    $nivelcurso = new Zend_Session_Namespace('nivel_curso');
    $nivel_curso = $nivelcurso->nivel_curso;

    if ($ingresonota == 1) { ?>

        <a class="button medium " href="<?php echo $this->url(array('controller' => 'Libro',
            'action' => 'abrir', 'id' => $id_curso), null, TRUE);
        ?>"><i class="icon-hand-left"></i> Volver</a>

    <?php } else {
        ?>


        <a class="button medium " href="<?php echo $this->url(array('controller' => 'Libro',
            'action' => 'abrir', 'id' => $id_curso . '-' . $id_detalle_curso), null, TRUE);
        ?>"><i class="icon-hand-left"></i> Volver</a>


    <?php } ?>

<?php }
if ($cargo->cargo == '1' || $cargo->cargo == '3') { ?>
    <a class="button medium blue" href="<?php echo $this->url(array('controller' => 'Libro',
        'action' => 'abrir', 'id' => $id_curso), null, TRUE);
    ?>"><i class="icon-hand-left"></i> Volver</a>
<?php } ?>

<div class="center-header">
    <div style="width: 40%">
        <?php if ($cargo->cargo == '2' || $cargo->cargo == '3' || $cargo->cargo == '6' || $cargo->cargo == '1') { ?>

            <a class="button medium blue" href="<?php echo $this->url(array('controller' => 'Libro',
                    'action' => 'agregacomunicaciones'), null, TRUE);
                ?>"> <i class="icon-plus"></i> Agregar Comunicación</a>

        <?php } ?>
    </div>
    <div style="width: 60%">
        <h3>Curso: <?php echo $nombre_curso; ?></h3>
    </div>

</div>





<div id="divTabla" style="margin-top: 20px;">
                    <label for="txtBuscar">Buscar: </label>
                    <input type="text" id="txtBuscar" autofocus
                           placeholder="Escriba el texto que desea encontrar y presione ENTER">
    <!--creo una tabla para mostrar los datos-->
    <table id="tblTabla" class="striped sortable" style="margin-top: 10px">
        <thead>
        <tr class="alt first last">
            <th>Comunicacion</th>
            <th>Tipo</th>
            <th>Enviar</th>
            <th>Eliminar</th>

        </tr>
        </thead>

        <!--    recorro el arreglo de datos-->
        <?php foreach ($this->listacitaciones as $f) { ?>
            <!--           por cada fila, muestro sus datos -->

            <tr>

                <td><?php echo $f[contenido]; ?>   </td>

                <td><?php
                    if ($f[idTipo] == '1') {
                        echo 'Reunión de Apoderados';
                    }
                    if ($f[idTipo] == '2') {
                        echo 'Citación de Apoderados';
                    }
                    if ($f[idTipo] == '3') {
                        echo 'Conducta';
                    }
                    if ($f[idTipo] == '4') {
                        echo 'Información';
                    }


                    ?></td>
                <td>
                    <a class="button medium blue" href="<?php echo $this->url(array('controller' => 'Libro',
                        'action' => 'enviarcomunicaciones', 'id' => $f[idComunicacion]), 'default', TRUE);
                    ?>"> <i class="icon-envelope"></i> Enviar Comunicación</a>
                </td>

                <td>


                    <a class="button small red"
                       onclick="if (confirm('¿Desea eliminar este registro?')) { document.location = this.href; } return false;"
                       href="<?php echo $this->url(array('controller' => 'Libro',
                           'action' => 'citacioneliminar', 'id' => $f[idComunicacion]), 'default', true); ?>"><i
                                class="icon-minus-sign"></i> Eliminar</a>


                </td>


            </tr>

            <!--    fin del for-->
        <?php }; ?>
    </table>



