<script src="<?php echo $this->baseUrl; ?>/javascript/buscador.js"></script>


<style>
    #divInfo {
        text-align: center;
        padding-bottom: 10px;
        margin-bottom: 40px;
    }

    #divTabla {

    }

    input[type="text"] {
        padding: 5px;
        width: 595px;
    }
</style>


<div id="divTabla" style="margin-top: 20px;">
                    <label for="txtBuscar">Buscar: </label>
                    <input type="text" id="txtBuscar" autofocus
                           placeholder="Escriba el texto que desea encontrar y presione ENTER">
    <!--creo una tabla para mostrar los datos-->
    <table id="tblTabla" class="striped sortable" style="margin-top: 10px">
        <thead>
        <tr>

            <th>Enseñanza</th>
            <th>Grado</th>
            <th>Letra</th>
            <th>Establecimiento</th>
            <th>Abrir libro</th>

        </tr>
        </thead>
        <?php
        $cargo = new Zend_Session_Namespace('cargo');
        $rol = $cargo->cargo;

        $ingreson = new Zend_Session_Namespace('ingresonota');
        $ingresonota = $ingreson->ingresonota;
        $datos = $this->datos;
        if ($rol == '2') {

            //if ($ingresonota == 1) {


            if (!empty($datos)) {


                ?>
                <?php foreach ($this->datos as $d) : ?>


                    <tr>


                        <td><?php echo $d['nombreTipoEnsenanza']; ?></td>

                        <td><?php echo $d['nombreGrado']; ?></td>

                        <td><?php echo $d['letra']; ?></td>

                        <td><?php echo $d['nombreEstablecimiento']; ?></td>

                        <td>

                            <a class="button small blue" href="<?php echo $this->url(array('controller' => 'Libro',
                                'action' => 'abrir', 'id' => $d['idCursos']), 'default', true); ?>"><i
                                        class="icon-hand-up"></i> Abrir</a>


                        </td>

                    </tr>

                <?php endforeach;
            }
            // } else {
//                if (!empty($datos)) {
//
//
//                    ?>
            <!--                    --><?php
//                    for ($i = 0; $i < count($datos); $i++) {
//
//                        foreach ($this->datos[$i] as $d[$i]) : ?>
            <!---->
            <!--                            <tr>-->
            <!---->
            <!--                                <td>--><?php //echo $d[$i]['nombreTipoEnsenanza']; ?><!--</td>-->
            <!---->
            <!--                                <td>--><?php //echo $d[$i]['nombreGrado']; ?><!--</td>-->
            <!---->
            <!--                                <td>--><?php //echo $d[$i]['letra']; ?><!--</td>-->
            <!---->
            <!--                                <td>--><?php //echo $d[$i]['nombreEstablecimiento']; ?><!--</td>-->
            <!---->
            <!--                                <td>-->
            <!---->
            <!--                                    <a class="button small blue"-->
            <!--                                       href="--><?php //echo $this->url(array('controller' => 'Libro',
//                                           'action' => 'abrir', 'id' => $d[$i]['idCursos'] . '-' . $d[$i]['idCuentaCurso']), 'default', true); ?><!--"><i-->
            <!--                                                class="icon-hand-up"></i> Abrir</a>-->
            <!---->
            <!---->
            <!--                                </td>-->
            <!---->
            <!--                            </tr>-->
            <!---->
            <!--                        --><?php //endforeach;
//                    }
//                }
            //}
        }

        if ($rol == '1' || $rol == '3' || $rol == '6') {

            ?>

            <?php foreach ($this->datos as $d) : ?>

                <tr>

                    <td><?php echo $d['nombreTipoEnsenanza']; ?></td>

                    <td><?php echo $d['nombreGrado']; ?></td>

                    <td><?php echo $d['letra']; ?></td>

                    <td><?php echo $d['nombreEstablecimiento']; ?>
                    </td>

                    <td>
                        <a class="button small blue" href="<?php echo $this->url(array('controller' => 'Libro',
                            'action' => 'abrir', 'id' => $d['idCursos']), 'default', true); ?>"><i
                                    class="icon-hand-up"></i> Abrir</a>


                    </td>

                </tr>

            <?php endforeach; ?>


        <?php } ?>
    </table>
