<script type="text/javascript"
        src="https://cdn.jsdelivr.net/npm/sweetalert2@7.32.4/dist/sweetalert2.all.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@7.29.2/dist/sweetalert2.min.css" type="text/css">




<?php
$establecimientos = new Zend_Session_Namespace('idesta');
$id_establecimiento = $establecimientos->idesta;


if ($id_establecimiento == 7) { ?>

<link href="<?php echo $this->baseUrl; ?>/css/monitoreo.css" type="text/css" rel="stylesheet"/>
<script src="<?php echo $this->baseUrl; ?>/javascript/monitoreogreda.js"></script>
    <?php if ($this->messages) {
        ?>

        <div class="error">
            <p>
                <?php foreach ($this->messages as $msg): ?>
                    <?php echo $msg; ?>
                <?php endforeach; ?>


            </p>

        </div>
        <a class="button medium blue" href="<?php echo $this->url(array('controller' => 'Libro',
            'action' => 'index'), null, true);
        ?>"><i class="icon-hand-left"></i> Volver</a>
    <?php } else {


        ?>

        <?php
        $nombrecurso = new Zend_Session_Namespace('nombre_curso');
        $nombre_curso = $nombrecurso->nombre_curso;

        $idcurso = new Zend_Session_Namespace('id_curso');
        $id_curso = $idcurso->id_curso;

        $iddetallecurso = new Zend_Session_Namespace('id_detalle_curso');
        $id_detalle_curso = $iddetallecurso->id_detalle_curso;

        $cargo = new Zend_Session_NameSpace("cargo");

        $ingreson = new Zend_Session_Namespace('ingresonota');
        $ingresonota = $ingreson->ingresonota;

        $codigos = new Zend_Session_Namespace('codigo');
        $codigo = $codigos->codigo;

        if ($cargo->cargo == '2') { ?>

            <?php
            $nivelcurso = new Zend_Session_Namespace('nivel_curso');
            $nivel_curso = $nivelcurso->nivel_curso; ?>



            <a class="button medium " href="<?php echo $this->url(array('controller' => 'Libro',
                'action' => 'abrir', 'id' => $id_curso), null, TRUE);
            ?>"><i class="icon-hand-left"></i> Volver</a>



        <?php }
        if ($cargo->cargo == '1' || $cargo->cargo == '3') { ?>
            <a class="button medium blue" href="<?php echo $this->url(array('controller' => 'Libro',
                'action' => 'abrir', 'id' => $id_curso), null, TRUE);
            ?>"><i class="icon-hand-left"></i> Volver</a>

        <?php } ?>

        <input type="hidden" id="apx" value="<?php echo $this->aprox; ?>">

        <div class="center-header">
            <div style="width: 40%">
                <?php if ($cargo->cargo == '2') { ?>

                    <div class="ventana">
                        <a class="button medium blue" id="nuevo"
                            href="<?php echo $this->url(array('controller' => 'Libro',
                                'action' => 'agregarguia', 'id' => ''), null, TRUE);
                            ?>"> Nueva Guía</a>

                    </div>

                    <div  style="margin-top: 8%; margin-bottom: 7%;" class="center">
                        <h4>

                        <?php


                            // RQM 42
                            if (!is_null($this->listaasignatura[0]['idNucleo'])) {

                                ?>
                                    <label for="ambito" class="required">Mostrar Núcleos por Ambito: </label>
                                    <select name="idAmbito" style="width: 260px;" id="sltAmbito">
                                <?php



                                foreach ($this->listaambitos as $ambito) : ?>

                                    <option value="<?php echo $ambito['idAmbito']; ?>"><?php echo $ambito['nombreAmbito']; ?></option>
                                    <?php
                                endforeach;

                                ?>
                                    </select>
                                <?php

                            }

                        ?>
                        </h4>
                    </div>

                <?php } ?>
            </div>
            <div style="width: 60%">
                <h3>Curso: <?php echo $nombre_curso; ?></h3>
            </div>

        </div>


        <ul class="tabs left" id="listas">
            <?php


            // RQM 42
            if (!is_null($this->listaasignatura[0]['idNucleo'])) {

                foreach ($this->listaasignatura as $c) :

                ?>

                    <li id="<?php echo $c['idAmbito']; ?>" class="asignaturali">
                        <a class="asignatura" href="#" id="<?php echo $c['idNucleo']; ?>" data-pre="true"
                           name="<?php echo $c['tipoAsignatura']; ?>" data-idAmbito="<?php echo $c['idAmbito']; ?>"><?php echo $c['nombreNucleo']; ?>
                        </a>
                    </li>
                    <?php
                endforeach;

            } else {
                foreach ($this->listaasignatura as $c) : ?>

                    <li>
                        <a class="asignatura" href="#" id="<?php echo $c['idAsignatura']; ?>"
                           name="<?php echo $c['tipoAsignatura']; ?>"><?php echo $c['nombreAsignatura']; ?>
                        </a>
                    </li>
                    <?php
                endforeach;

            }


            ?>
        </ul>
        <input type="hidden" id="us" value="<?php echo $cargo->cargo; ?>">

        <div class="grid-container" id="tblTabla">
            <div class="grid">
                <div class="grid-col grid-col--fixed-left alumnos" id="alumnos">
                    <div class="grid-item grid-item--header">
                        <p class="head">Alumnos</p>
                    </div>
                    <?php foreach ($this->alumnos as $c) : ?>
                        <div id="alum" name="<?php echo $c['idAlumnosActual']; ?>" class="grid-item"
                             style="text-align: left; width: auto;">
                            <p><?php echo $c['apaterno'] . ' ' . $c['amaterno'] . ' ' . $c['nombres']; ?> </p>
                        </div>
                    <?php endforeach; ?>

                    <div id="alum" name="entregadaheader" class="grid-item"
                         style="text-align: left; width: auto;background-color: green;">
                        <p style="color: white">Entregada </p>
                    </div>

                    <div id="alum" name="noentregadaheader" class="grid-item"
                         style="text-align: left; width: auto;background-color: red;">
                        <p style="color: white">No Entregada </p>
                    </div>

                    <div id="alum" name="revisadaheader" class="grid-item"
                         style="text-align: left; width: auto;background-color: cyan">
                        <p>Retroalimentada</p>
                    </div>

                    <div id="alum" name="revisainheader" class="grid-item"
                         style="text-align: left; width: auto;background-color: yellow">
                        <p>Evaluada Formativamente </p>
                    </div>


                </div>

                <div class="grid-col primer" id="primer" style="display: none">
                    <div class="grid-item grid-item--header" style="background-color: #11b106;">
                        <p class="head">I SEM</p>
                    </div>
                    <?php /*foreach ($this->alumnos as $c) : */ ?>
                    <div class="grid-item sem">
                    </div>
                    <?php /*endforeach; */ ?>
                </div>

                <div class="grid-col segundo" id="segundo" style="display: none">
                    <div class="grid-item grid-item--header" style="background-color: #11b106;">
                        <p class="head">II SEM</p>
                    </div>
                    <?php /*foreach ($this->alumnos as $c) : */ ?>
                    <div class="grid-item sem">
                    </div>
                    <?php /*endforeach; */ ?>
                </div>


                <div class="grid-col grid-col--fixed-right" id="entregada"
                     style="width: 70px;right: 270px;background-color: whitesmoke">
                    <div class="grid-item grid-item--header final" style="background-color: green; color: white">
                        <p class="head" style="color: white">Total Entregada</p>
                    </div>
                    <?php foreach ($this->alumnos as $c) : ?>
                        <div class="grid-item entregada<?php echo $c['idAlumnosActual']; ?>"
                             style="background-color: green; color: white;">
                            <p></p>
                        </div>
                    <?php endforeach; ?>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>

                </div>

                <div class="grid-col grid-col--fixed-right" id="noentregada"
                     style="width: 70px;right: 200px;background-color: whitesmoke">
                    <div class="grid-item grid-item--header final" style="background-color: red">
                        <p class="head" style="color: white">Total No Entregada</p>
                    </div>
                    <?php foreach ($this->alumnos as $c) : ?>
                        <div class="grid-item noentregada<?php echo $c['idAlumnosActual']; ?> "
                             style="background-color: red">
                            <p></p>
                        </div>
                    <?php endforeach; ?>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>

                </div>

                <div class="grid-col grid-col--fixed-right" id="revisada"
                     style="width: 110px;right: 100px;background-color: whitesmoke">
                    <div class="grid-item grid-item--header final" style="background-color: cyan">
                        <p class="head">Total Retroalimentada</p>
                    </div>
                    <?php foreach ($this->alumnos as $c) : ?>
                        <div class="grid-item revisada<?php echo $c['idAlumnosActual']; ?>"
                             style="background-color: cyan">
                            <p></p>
                        </div>
                    <?php endforeach; ?>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>

                </div>


                <div class="grid-col grid-col--fixed-right" id="revisadaincompleta"
                     style="width: 110px;right:0px;background-color: whitesmoke">
                    <div class="grid-item grid-item--header final" style="background-color: yellow">
                        <p class="head">Total Evaluada Formativamente</p>
                    </div>
                    <?php foreach ($this->alumnos as $c) : ?>
                        <div class="grid-item revisadain<?php echo $c['idAlumnosActual']; ?>"
                             style="background-color: yellow">
                            <p></p>
                        </div>
                    <?php endforeach; ?>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>

                </div>

            </div>
        </div>


        <?php

    }


}//FIN LA GREDA

//INICIO CGV
else if($id_establecimiento==11){ ?>


    <link href="<?php echo $this->baseUrl; ?>/css/monitoreocgv.css" type="text/css" rel="stylesheet"/>
    <script src="<?php echo $this->baseUrl; ?>/javascript/monitoreocgv.js"></script>

    <?php if ($this->messages) {
        ?>

        <div class="error">
            <p>
                <?php foreach ($this->messages as $msg): ?>
                    <?php echo $msg; ?>
                <?php endforeach; ?>


            </p>

        </div>
        <a class="button medium blue" href="<?php echo $this->url(array('controller' => 'Libro',
            'action' => 'index'), null, true);
        ?>"><i class="icon-hand-left"></i> Volver</a>
    <?php } else {


        ?>

        <?php
        $nombrecurso = new Zend_Session_Namespace('nombre_curso');
        $nombre_curso = $nombrecurso->nombre_curso;

        $idcurso = new Zend_Session_Namespace('id_curso');
        $id_curso = $idcurso->id_curso;

        $iddetallecurso = new Zend_Session_Namespace('id_detalle_curso');
        $id_detalle_curso = $iddetallecurso->id_detalle_curso;

        $cargo = new Zend_Session_NameSpace("cargo");

        $ingreson = new Zend_Session_Namespace('ingresonota');
        $ingresonota = $ingreson->ingresonota;

        $codigos = new Zend_Session_Namespace('codigo');
        $codigo = $codigos->codigo;

        if ($cargo->cargo == '2') { ?>

            <?php
            $nivelcurso = new Zend_Session_Namespace('nivel_curso');
            $nivel_curso = $nivelcurso->nivel_curso;
            if ($ingresonota == 1) { ?>

                <a class="button medium " href="<?php echo $this->url(array('controller' => 'Libro',
                    'action' => 'abrir', 'id' => $id_curso), null, TRUE);
                ?>"><i class="icon-hand-left"></i> Volver</a>

            <?php } else {
                ?>


                <a class="button medium " href="<?php echo $this->url(array('controller' => 'Libro',
                    'action' => 'abrir', 'id' => $id_curso . '-' . $id_detalle_curso), null, TRUE);
                ?>"><i class="icon-hand-left"></i> Volver</a>

            <?php } ?>


            <a class="button medium green" href="<?php echo $this->url(array('controller' => 'Libro',
                'action' => 'notasnuevo'), null, TRUE);
            ?>"><i class="icon-hand-left"></i> Ir a Notas</a>


        <?php }
        if ($cargo->cargo == '1' || $cargo->cargo == '3') { ?>
            <a class="button medium blue" href="<?php echo $this->url(array('controller' => 'Libro',
                'action' => 'abrir', 'id' => $id_curso), null, TRUE);
            ?>"><i class="icon-hand-left"></i> Volver</a>
            <a class="button medium green" href="<?php echo $this->url(array('controller' => 'Libro',
                'action' => 'notasnuevo'), null, TRUE);
            ?>"><i class="icon-hand-left"></i> Ir a Notas</a>
        <?php } ?>

        <input type="hidden" id="apx" value="<?php echo $this->aprox; ?>">

        <div class="center-header">
            <div style="width: 40%">
                <?php if ($cargo->cargo == '2') { ?>

                    <div class="ventana"><a class="button medium blue" id="nuevo"
                                            href="<?php echo $this->url(array('controller' => 'Libro',
                                                'action' => 'agregarguia', 'id' => ''), null, TRUE);
                                            ?>"> Nueva Guía</a></div>


                <?php } ?>
            </div>
            <div style="width: 60%">
                <h3>Curso: <?php echo $nombre_curso; ?></h3>
            </div>

        </div>


        <ul class="tabs left" id="listas">
            <?php
            foreach ($this->listaasignatura as $c) : ?>

                <li><a class="asignatura" href="#" id="<?php echo $c['idAsignatura']; ?>"
                       name="<?php echo $c['tipoAsignatura']; ?>"><?php echo $c['nombreAsignatura']; ?></a></li>


            <?php endforeach;
            ?>
        </ul>
        <input type="hidden" id="us" value="<?php echo $cargo->cargo; ?>">

        <div class="grid-container" id="tblTabla">
            <div class="grid">
                <div class="grid-col grid-col--fixed-left alumnos" id="alumnos">
                    <div class="grid-item grid-item--header">
                        <p class="head">Alumnos</p>
                    </div>
                    <?php foreach ($this->alumnos as $c) : ?>
                        <div id="alum" name="<?php echo $c['idAlumnosActual']; ?>" class="grid-item"
                             style="text-align: left; width: auto;">
                            <p><?php echo $c['apaterno'] . ' ' . $c['amaterno'] . ' ' . $c['nombres']; ?> </p>
                        </div>
                    <?php endforeach; ?>


                    <div id="alum" name="totalesheader" class="grid-item"
                         style="text-align: center; width: auto; height: 80px">
                        <p style="font-size: 18px">Total</p>
                    </div>


                </div>


                <div class="grid-col segundo" id="segundo" style="display: none">
                    <div class="grid-item grid-item--header" style="background-color: #11b106;">
                        <p class="head">II SEM</p>
                    </div>
                    <?php /*foreach ($this->alumnos as $c) : */ ?>
                    <div class="grid-item sem">
                    </div>
                    <?php /*endforeach; */ ?>
                </div>


<!--                <div class="grid-col grid-col--fixed-right" id="entregada"-->
<!--                     style="width: 70px;right: 0px;background-color: whitesmoke">-->
<!--                    <div class="grid-item grid-item--header final" style="background-color: green; color: white">-->
<!--                        <p class="head" style="color: white">Total Entregada</p>-->
<!--                    </div>-->
<!--                    --><?php //foreach ($this->alumnos as $c) : ?>
<!--                        <div class="grid-item entregada--><?php //echo $c['idAlumnosActual']; ?><!--"-->
<!--                             style="background-color: green; color: white;">-->
<!--                            <p></p>-->
<!--                        </div>-->
<!--                    --><?php //endforeach; ?>
<!---->
<!---->
<!--                </div>-->


            </div>
        </div>


        <?php

    }


}else if ($id_establecimiento == 14) { ?>

    <link href="<?php echo $this->baseUrl; ?>/css/monitoreo.css" type="text/css" rel="stylesheet"/>
    <script src="<?php echo $this->baseUrl; ?>/javascript/monitoreohorcon.js"></script>
    <?php if ($this->messages) {
        ?>

        <div class="error">
            <p>
                <?php foreach ($this->messages as $msg): ?>
                    <?php echo $msg; ?>
                <?php endforeach; ?>


            </p>

        </div>
        <a class="button medium blue" href="<?php echo $this->url(array('controller' => 'Libro',
            'action' => 'index'), null, true);
        ?>"><i class="icon-hand-left"></i> Volver</a>
    <?php } else {


        ?>

        <?php
        $nombrecurso = new Zend_Session_Namespace('nombre_curso');
        $nombre_curso = $nombrecurso->nombre_curso;

        $idcurso = new Zend_Session_Namespace('id_curso');
        $id_curso = $idcurso->id_curso;

        $iddetallecurso = new Zend_Session_Namespace('id_detalle_curso');
        $id_detalle_curso = $iddetallecurso->id_detalle_curso;

        $cargo = new Zend_Session_NameSpace("cargo");

        $ingreson = new Zend_Session_Namespace('ingresonota');
        $ingresonota = $ingreson->ingresonota;

        $codigos = new Zend_Session_Namespace('codigo');
        $codigo = $codigos->codigo;

        if ($cargo->cargo == '2') { ?>

            <?php
            $nivelcurso = new Zend_Session_Namespace('nivel_curso');
            $nivel_curso = $nivelcurso->nivel_curso; ?>



            <a class="button medium " href="<?php echo $this->url(array('controller' => 'Libro',
                'action' => 'abrir', 'id' => $id_curso), null, TRUE);
            ?>"><i class="icon-hand-left"></i> Volver</a>

            <a class="button medium green" href="<?php echo $this->url(array('controller' => 'Libro',
                'action' => 'notasnuevo'), null, TRUE);
            ?>"><i class="icon-hand-left"></i> Ir a Notas</a>


        <?php }
        if ($cargo->cargo == '1' || $cargo->cargo == '3') { ?>
            <a class="button medium blue" href="<?php echo $this->url(array('controller' => 'Libro',
                'action' => 'abrir', 'id' => $id_curso), null, TRUE);
            ?>"><i class="icon-hand-left"></i> Volver</a>
            <a class="button medium green" href="<?php echo $this->url(array('controller' => 'Libro',
                'action' => 'notasnuevo'), null, TRUE);
            ?>"><i class="icon-hand-left"></i> Ir a Notas</a>
        <?php } ?>

        <input type="hidden" id="apx" value="<?php echo $this->aprox; ?>">

        <div class="center-header">
            <div style="width: 40%">
                <?php if ($cargo->cargo == '2') { ?>

                    <div class="ventana"><a class="button medium blue" id="nuevo"
                                            href="<?php echo $this->url(array('controller' => 'Libro',
                                                'action' => 'agregarguia', 'id' => ''), null, TRUE);
                                            ?>"> Nueva Guía</a></div>


                <?php } ?>
            </div>
            <div style="width: 60%">
                <h3>Curso: <?php echo $nombre_curso; ?></h3>
            </div>

        </div>


        <ul class="tabs left" id="listas">
            <?php
            foreach ($this->listaasignatura as $c) : ?>

                <li><a class="asignatura" href="#" id="<?php echo $c['idAsignatura']; ?>"
                       name="<?php echo $c['tipoAsignatura']; ?>"><?php echo $c['nombreAsignatura']; ?></a></li>


            <?php endforeach;
            ?>
        </ul>
        <input type="hidden" id="us" value="<?php echo $cargo->cargo; ?>">

        <div class="grid-container" id="tblTabla">
            <div class="grid">
                <div class="grid-col grid-col--fixed-left alumnos" id="alumnos">
                    <div class="grid-item grid-item--header">
                        <p class="head">Alumnos</p>
                    </div>
                    <?php foreach ($this->alumnos as $c) : ?>
                        <div id="alum" name="<?php echo $c['idAlumnosActual']; ?>" class="grid-item"
                             style="text-align: left; width: auto;">
                            <p><?php echo $c['apaterno'] . ' ' . $c['amaterno'] . ' ' . $c['nombres']; ?> </p>
                        </div>
                    <?php endforeach; ?>

                    <div id="alum" name="entregadaheader" class="grid-item"
                         style="text-align: left; width: auto;background-color: pink;">
                        <p>Entregada </p>
                    </div>

                    <div id="alum" name="noentregadaheader" class="grid-item"
                         style="text-align: left; width: auto;background-color: blue;">
                        <p style="color: white">No Entregada </p>
                    </div>

                    <div id="alum" name="revisadaheader" class="grid-item"
                         style="text-align: left; width: auto;background-color: yellow">
                        <p>Retroalimentada</p>
                    </div>

                    <div id="alum" name="revisainheader" class="grid-item"
                         style="text-align: left; width: auto;background-color: darkgreen">
                        <p style="color:white;">Evaluada Formativamente </p>
                    </div>


                </div>

                <div class="grid-col primer" id="primer" style="display: none">
                    <div class="grid-item grid-item--header" style="background-color: #11b106;">
                        <p class="head">I SEM</p>
                    </div>
                    <?php /*foreach ($this->alumnos as $c) : */ ?>
                    <div class="grid-item sem">
                    </div>
                    <?php /*endforeach; */ ?>
                </div>

                <div class="grid-col segundo" id="segundo" style="display: none">
                    <div class="grid-item grid-item--header" style="background-color: #11b106;">
                        <p class="head">II SEM</p>
                    </div>
                    <?php /*foreach ($this->alumnos as $c) : */ ?>
                    <div class="grid-item sem">
                    </div>
                    <?php /*endforeach; */ ?>
                </div>


                <div class="grid-col grid-col--fixed-right" id="entregada"
                     style="width: 70px;right: 270px;background-color: whitesmoke">
                    <div class="grid-item grid-item--header final" style="background-color: pink;">
                        <p class="head">Total Entregada</p>
                    </div>
                    <?php foreach ($this->alumnos as $c) : ?>
                        <div class="grid-item entregada<?php echo $c['idAlumnosActual']; ?>"
                             style="background-color: pink;">
                            <p></p>
                        </div>
                    <?php endforeach; ?>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>

                </div>

                <div class="grid-col grid-col--fixed-right" id="noentregada"
                     style="width: 70px;right: 200px;background-color: whitesmoke">
                    <div class="grid-item grid-item--header final" style="background-color: blue">
                        <p class="head" style="color: white">Total No Entregada</p>
                    </div>
                    <?php foreach ($this->alumnos as $c) : ?>
                        <div class="grid-item noentregada<?php echo $c['idAlumnosActual']; ?> "
                             style="background-color: blue">
                            <p></p>
                        </div>
                    <?php endforeach; ?>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>

                </div>

                <div class="grid-col grid-col--fixed-right" id="revisada"
                     style="width: 110px;right: 100px;background-color: whitesmoke">
                    <div class="grid-item grid-item--header final" style="background-color: yellow">
                        <p class="head">Total Retroalimentada</p>
                    </div>
                    <?php foreach ($this->alumnos as $c) : ?>
                        <div class="grid-item revisada<?php echo $c['idAlumnosActual']; ?>"
                             style="background-color: yellow">
                            <p></p>
                        </div>
                    <?php endforeach; ?>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>

                </div>


                <div class="grid-col grid-col--fixed-right" id="revisadaincompleta"
                     style="width: 110px;right:0px;background-color: whitesmoke">
                    <div class="grid-item grid-item--header final" style="background-color: darkgreen">
                        <p style="color: white;" class="head">Total Evaluada Formativamente</p>
                    </div>
                    <?php foreach ($this->alumnos as $c) : ?>
                        <div class="grid-item revisadain<?php echo $c['idAlumnosActual']; ?>"
                             style="background-color: darkgreen">
                            <p></p>
                        </div>
                    <?php endforeach; ?>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>

                </div>

            </div>
        </div>


        <?php

    }

}else if($id_establecimiento==12){ ?>


    <link href="<?php echo $this->baseUrl; ?>/css/monitoreocesa.css" type="text/css" rel="stylesheet"/>
    <script src="<?php echo $this->baseUrl; ?>/javascript/monitoreocesa_v3.1.js"></script>


    <?php if ($this->messages) {
        ?>

        <div class="error">
            <p>
                <?php foreach ($this->messages as $msg): ?>
                    <?php echo $msg; ?>
                <?php endforeach; ?>


            </p>

        </div>
        <a class="button medium blue" href="<?php echo $this->url(array('controller' => 'Libro',
            'action' => 'index'), null, true);
        ?>"><i class="icon-hand-left"></i> Volver</a>
    <?php } else {


        ?>

        <?php
        $nombrecurso = new Zend_Session_Namespace('nombre_curso');
        $nombre_curso = $nombrecurso->nombre_curso;

        $idcurso = new Zend_Session_Namespace('id_curso');
        $id_curso = $idcurso->id_curso;

        $iddetallecurso = new Zend_Session_Namespace('id_detalle_curso');
        $id_detalle_curso = $iddetallecurso->id_detalle_curso;

        $cargo = new Zend_Session_NameSpace("cargo");

        $ingreson = new Zend_Session_Namespace('ingresonota');
        $ingresonota = $ingreson->ingresonota;

        $codigos = new Zend_Session_Namespace('codigo');
        $codigo = $codigos->codigo;

        if ($cargo->cargo == '2') { ?>

            <?php
            $nivelcurso = new Zend_Session_Namespace('nivel_curso');
            $nivel_curso = $nivelcurso->nivel_curso; ?>



            <a class="button medium " href="<?php echo $this->url(array('controller' => 'Libro',
                'action' => 'abrir', 'id' => $id_curso), null, TRUE);
            ?>"><i class="icon-hand-left"></i> Volver</a>

            <a class="button medium green" href="<?php echo $this->url(array('controller' => 'Libro',
                'action' => 'notasnuevo'), null, TRUE);
            ?>"><i class="icon-hand-left"></i> Ir a Notas</a>


        <?php }
        if ($cargo->cargo == '1' || $cargo->cargo == '3') { ?>
            <a class="button medium blue" href="<?php echo $this->url(array('controller' => 'Libro',
                'action' => 'abrir', 'id' => $id_curso), null, TRUE);
            ?>"><i class="icon-hand-left"></i> Volver</a>
            <a class="button medium green" href="<?php echo $this->url(array('controller' => 'Libro',
                'action' => 'notasnuevo'), null, TRUE);
            ?>"><i class="icon-hand-left"></i> Ir a Notas</a>
        <?php } ?>

        <input type="hidden" id="apx" value="<?php echo $this->aprox; ?>">

        <div class="center-header">
            <div style="width: 40%">
                <?php if ($cargo->cargo == '2') { ?>

                    <div class="ventana"><a class="button medium blue" id="nuevo"
                                            href="<?php echo $this->url(array('controller' => 'Libro',
                                                'action' => 'agregarguianotas', 'id' => ''), null, TRUE);
                                            ?>"> Nueva Guía</a></div>


                <?php } ?>
            </div>
            <div style="width: 60%">
                <h3>Curso: <?php echo $nombre_curso; ?></h3>
            </div>

        </div>


        <ul class="tabs left" id="listas">
            <?php
            foreach ($this->listaasignatura as $c) : ?>

                <li><a class="asignatura" href="#" id="<?php echo $c['idAsignatura']; ?>"
                       name="<?php echo $c['tipoAsignatura']; ?>"><?php echo $c['nombreAsignatura']; ?></a></li>


            <?php endforeach;
            ?>
        </ul>
        <input type="hidden" id="us" value="<?php echo $cargo->cargo; ?>">

        <div class="grid-container" id="tblTabla">
            <div class="grid">
                <div class="grid-col grid-col--fixed-left alumnos" id="alumnos">
                    <div class="grid-item grid-item--header">
                        <p class="head">Alumnos</p>
                    </div>
                    <?php foreach ($this->alumnos as $c) : ?>
                        <div id="alum" name="<?php echo $c['idAlumnosActual']; ?>" class="grid-item"
                             style="text-align: left; width: auto;">
                            <p><?php echo $c['apaterno'] . ' ' . $c['amaterno'] . ' ' . $c['nombres']; ?> </p>
                        </div>
                    <?php endforeach; ?>


                    <div id="alum" name="totalesheader" class="grid-item"
                         style="text-align: center; width: auto; height: 80px">
                        <p style="font-size: 18px">Total</p>
                    </div>


                </div>


                <div class="grid-col primer" id="primer">
                    <div class="grid-item grid-item--header" style="background-color: #11b106;">
                        <p class="head">% Logro</p>
                        <p class="head">I Sem</p>
                    </div>
                    <?php  foreach ($this->alumnos as $c) :  ?>
                    <div class="grid-item sem porcentaje" name="<?php echo $c['idAlumnosActual']; ?>" style="width: 62px">
                    </div>
                    <?php  endforeach; ?>
                    <div id="alum" name="totalesheader" class="grid-item"
                         style="text-align: center; width: auto; height: 80px">
                        <p></p>
                    </div>
                </div>
                <div class="grid-col primerl" id="primerl">
                    <div class="grid-item grid-item--header" style="background-color: #11b106;">
                        <p class="head">Nivel Logro</p>
                        <p class="head">I Sem</p>
                    </div>
                    <?php foreach ($this->alumnos as $c) :  ?>
                        <div class="grid-item sem nivel" name="<?php echo $c['idAlumnosActual']; ?>">
                        </div>
                    <?php endforeach; ?>
                    <div id="alum" name="totalesheader" class="grid-item"
                         style="text-align: center; width: auto; height: 80px">
                        <p></p>
                    </div>
                </div>
                <div class="grid-col primern" id="primern">
                    <div class="grid-item grid-item--header" style="background-color: #11b106;">
                        <p class="head">Nota Final</p>
                        <p class="head">I Sem</p>
                    </div>
                    <?php foreach ($this->alumnos as $c) :  ?>
                        <div class="grid-item sem nota_final" name="<?php echo $c['idAlumnosActual']; ?>">
                        </div>
                    <?php endforeach; ?>
                    <div id="alum" name="totalesheader" class="grid-item"
                         style="text-align: center; width: auto; height: 80px">
                        <p></p>
                    </div>
                </div>



                <div class="grid-col segundo" id="segundo">
                    <div class="grid-item grid-item--header" style="background-color: #11b106;">
                        <p class="head">% Logro</p>
                        <p class="head">II SEM</p>
                    </div>
                    <?php  foreach ($this->alumnos as $c) :  ?>
                    <div class="grid-item sem porcentaje_sem2" name="<?php echo $c['idAlumnosActual']; ?>" style="width: 62px">
                    </div>
                    <?php  endforeach; ?>
                    <div id="alum" name="totalesheader" class="grid-item"
                         style="text-align: center; width: auto; height: 80px">
                        <p></p>
                    </div>
                </div>
                <div class="grid-col segundol" id="segundol">
                    <div class="grid-item grid-item--header" style="background-color: #11b106;">
                        <p class="head">Nivel Logro</p>
                        <p class="head">II SEM</p>
                    </div>
                    <?php foreach ($this->alumnos as $c) :  ?>
                        <div class="grid-item sem nivel_sem2" name="<?php echo $c['idAlumnosActual']; ?>">
                        </div>
                    <?php endforeach; ?>
                    <div id="alum" name="totalesheader" class="grid-item"
                         style="text-align: center; width: auto; height: 80px">
                        <p></p>
                    </div>
                </div>
                <div class="grid-col segundon" id="segundon">
                    <div class="grid-item grid-item--header" style="background-color: #11b106;">
                        <p class="head">Nota Final</p>
                        <p class="head">II SEM</p>
                    </div>
                    <?php foreach ($this->alumnos as $c) :  ?>
                        <div class="grid-item sem nota_final_sem2" name="<?php echo $c['idAlumnosActual']; ?>">
                        </div>
                    <?php endforeach; ?>
                    <div id="alum" name="totalesheader" class="grid-item"
                         style="text-align: center; width: auto; height: 80px">
                        <p></p>
                    </div>
                </div>

            </div>
        </div>


        <?php

    }

//Inicio Laguna
}else if($id_establecimiento==8){ ?>


    <link href="<?php echo $this->baseUrl; ?>/css/monitoreolaguna.css" type="text/css" rel="stylesheet"/>
    <script src="<?php echo $this->baseUrl; ?>/javascript/monitoreolaguna.js"></script>

    <?php if ($this->messages) {
        ?>

        <div class="error">
            <p>
                <?php foreach ($this->messages as $msg): ?>
                    <?php echo $msg; ?>
                <?php endforeach; ?>


            </p>

        </div>
        <a class="button medium blue" href="<?php echo $this->url(array('controller' => 'Libro',
            'action' => 'index'), null, true);
        ?>"><i class="icon-hand-left"></i> Volver</a>
    <?php } else {


        ?>

        <?php
        $nombrecurso = new Zend_Session_Namespace('nombre_curso');
        $nombre_curso = $nombrecurso->nombre_curso;

        $idcurso = new Zend_Session_Namespace('id_curso');
        $id_curso = $idcurso->id_curso;

        $iddetallecurso = new Zend_Session_Namespace('id_detalle_curso');
        $id_detalle_curso = $iddetallecurso->id_detalle_curso;

        $cargo = new Zend_Session_NameSpace("cargo");

        $ingreson = new Zend_Session_Namespace('ingresonota');
        $ingresonota = $ingreson->ingresonota;

        $codigos = new Zend_Session_Namespace('codigo');
        $codigo = $codigos->codigo;

        if ($cargo->cargo == '2') { ?>

            <?php
            $nivelcurso = new Zend_Session_Namespace('nivel_curso');
            $nivel_curso = $nivelcurso->nivel_curso;
            if ($ingresonota == 1) { ?>

                <a class="button medium " href="<?php echo $this->url(array('controller' => 'Libro',
                    'action' => 'abrir', 'id' => $id_curso), null, TRUE);
                ?>"><i class="icon-hand-left"></i> Volver</a>

            <?php } else {
                ?>


                <a class="button medium " href="<?php echo $this->url(array('controller' => 'Libro',
                    'action' => 'abrir', 'id' => $id_curso . '-' . $id_detalle_curso), null, TRUE);
                ?>"><i class="icon-hand-left"></i> Volver</a>

            <?php }


       }
        if ($cargo->cargo == '1' || $cargo->cargo == '3') { ?>
            <a class="button medium blue" href="<?php echo $this->url(array('controller' => 'Libro',
                'action' => 'abrir', 'id' => $id_curso), null, TRUE);
            ?>"><i class="icon-hand-left"></i> Volver</a>

        <?php } ?>

        <input type="hidden" id="apx" value="<?php echo $this->aprox; ?>">

        <div class="center-header">
            <div style="width: 40%">
                <?php if ($cargo->cargo == '2') { ?>

                    <div class="ventana"><a class="button medium blue" id="nuevo"
                                            href="<?php echo $this->url(array('controller' => 'Libro',
                                                'action' => 'agregarguialag', 'id' => ''), null, TRUE);
                                            ?>"> Nueva Evaluación</a></div>


                <?php } ?>
            </div>
            <div style="width: 60%">
                <h3>Curso: <?php echo $nombre_curso; ?></h3>
            </div>

        </div>


        <ul class="tabs left" id="listas">
            <?php
            foreach ($this->listaasignatura as $c) : ?>

                <li><a class="asignatura" href="#" id="<?php echo $c['idAsignatura']; ?>"
                       name="<?php echo $c['tipoAsignatura']; ?>"><?php echo $c['nombreAsignatura']; ?></a></li>


            <?php endforeach;
            ?>
        </ul>
        <input type="hidden" id="us" value="<?php echo $cargo->cargo; ?>">

        <div class="grid-container" id="tblTabla">
            <div class="grid">
                <div class="grid-col grid-col--fixed-left alumnos" id="alumnos">
                    <div class="grid-item grid-item--header">
                        <p class="head">Alumnos</p>
                    </div>
                    <?php foreach ($this->alumnos as $c) : ?>
                        <div id="alum" name="<?php echo $c['idAlumnosActual']; ?>" class="grid-item"
                             style="text-align: left; width: auto;">
                            <p><?php echo $c['apaterno'] . ' ' . $c['amaterno'] . ' ' . $c['nombres']; ?> </p>
                        </div>
                    <?php endforeach; ?>


                </div>

                <div class="grid-col primer" id="primer">
                    <div class="grid-item grid-item--header" style="background-color: #11b106;">
                        <p class="head">I SEM</p>
                    </div>
                    <?php foreach ($this->alumnos as $c) :  ?>
                    <div class="grid-item sem">
                    </div>
                    <?php endforeach;  ?>
                </div>


                <div class="grid-col segundo" id="segundo">
                    <div class="grid-item grid-item--header" style="background-color: #11b106;">
                        <p class="head">II SEM</p>
                    </div>
                    <?php foreach ($this->alumnos as $c) :  ?>
                    <div class="grid-item sem">
                    </div>
                    <?php endforeach; ?>
                </div>

                <div class="grid-col grid-col--fixed-right " id="final">
                    <div class="grid-item grid-item--header final" style="background-color: #63abe6;">
                        <p class="head">FINAL</p>
                    </div>
                    <?php foreach ($this->alumnos as $c) : ?>
                        <div class="grid-item final">
                        </div>
                    <?php endforeach; ?>
                </div>

            </div>
        </div>


        <?php

    }


}






