<script src="<?php echo $this->baseUrl; ?>/javascript/buscador.js"></script>

<style>
    #divInfo{
		text-align: center;
		padding-bottom: 10px;
		margin-bottom: 40px;
	}
	#divTabla{
		
	}
		input[type="text"]{
			padding: 5px;
			width: 595px;
		}
</style>
<?php
       $idcurso= new Zend_Session_Namespace('id_curso');
       $id_curso=$idcurso->id_curso;
       
       $iddetallecurso= new Zend_Session_Namespace('id_detalle_curso');
       $id_detalle_curso=$iddetallecurso->id_detalle_curso;
       
       $roles= new Zend_Session_Namespace('cargo');
       $rol=$roles->cargo;
       
       ?>
<?php if($rol=='3' || $rol=='1' ){ ?>
<a class="button medium blue" href="<?php echo $this->url(array('controller' => 'Libro',
    'action' => 'abrir','id'=>$id_curso), null, TRUE);
?>"><i class="icon-hand-left"></i> Volver</a>
<?php } ?>

<?php if($rol=='2'){ ?>
<a class="button medium blue" href="<?php echo $this->url(array('controller' => 'Libro',
    'action' => 'abrir','id'=>$id_curso), null, TRUE);
?>"><i class="icon-hand-left"></i> Volver</a>

<a class="button medium blue" href="<?php echo $this->url(array('controller' => 'Libro',
    'action' => 'agregapruebas'), null, TRUE);
?>"> <i class="icon-plus"></i> Agregar Prueba</a>

<?php } ?>

<?php if($rol=='3' || $rol=='1' || $rol=='2'){ ?>
<!--  Link agrega notas-->




	<div id="divTabla" style="margin-top: 20px;">
                <label for="txtBuscar">Buscar: </label>
                <input type="text" id="txtBuscar" autofocus placeholder="Escriba el texto que desea encontrar y presione ENTER">
<!--creo una tabla para mostrar los datos-->
<table id="tblTabla" class="striped sortable" style="margin-top: 10px">
    <thead>
    <tr>
        
        <th>Contenido</th>
        <th>Periodo Evaluación</th>
        <th>Curso</th>
        <th>Asignatura</th>
        <th>Estado</th>
        <th>Coeficiente</th>
        <th>Fecha</th>
        <th>Documentos</th>
        <th>Editar</th>  
        <th>Eliminar</th>
        
    </tr>
    </thead> 
<?php $var0=$this->datospruebas;
if(!empty($var0)){



?>
<!--    recorro el arreglo de datos-->
    <?php foreach ($this->datospruebas as $d) : ?>
<!--           por cada fila, muestro sus datos -->

        <tr>
          
           
<td><?php echo $d[contenido]; ?></td>

<td><?php 

if($d[tiempo]=='1'){
    echo 'Primer Semestre';
    
}
if($d[tiempo]=='2'){
    echo 'Segundo Semestre';
    
}
if($d[tiempo]=='3'){
    echo 'Primer Trimestre';
    
}
if($d[tiempo]=='4'){
    echo 'Segundo Trimestre';
    
}
if($d[tiempo]=='5'){
    echo 'Tercer Trimestre';
    
}

 ?>

</td>

        <td><?php echo $d[nombreCursos]; ?></td>
        
              
        <td><?php echo $d[nombreAsignatura]; ?>
        </td>
        <?php if ($d[estadoev]=='0') { ?>
        <td>Sin Calificaciones</td>
            
       <?php }else{ ?>
        <td>Con Calificaciones</td>
       <?php } ?>


        <?php if ($d[coef]=='1') { ?>
        <td>Coeficiente 1</td>
            
       <?php }if ($d[coef]=='2') { ?>
        <td>Coeficiente 2</td>
       <?php }if ($d[coef]=='0') { ?>
       <td>Sin Asignar</td>
       <?php } ?>

       <td>
         <?php 
        $fechainicial=$d[fechaEvaluacion];
        $date = new DateTime($fechainicial);
        echo $date->format('d-m-Y'); ?>
       </td>

        
        
         <?php if($d[guia]!='0' || empty($d[guia])){ ?>
        <td><div class="ventana">
            <a class="button small blue" href="<?php echo $this->url(array('controller' => 'Libro',
                       'action' => 'verpruebas', 'id'=>$d[idPruebas]), 'default', true); ?>"><i class="icon-eye-open"></i> Ver Documentos</a>
            </div>
            </td>
            
       <?php }else{ ?>
        <td><a class="button small gray" disabled="disabled" ><i class="icon-eye-open"></i> Ver Documentos</a>
            </td>
       <?php } ?>
         
           
         
             <td>
            
            
            <a class="button small green" href="<?php echo $this->url(array('controller' => 'Libro',
                       'action' => 'pruebaeditar', 'id'=>$d[idEvaluacion]), 'default', true); ?>"><i class="icon-edit"></i> Editar</a>
            
            
            </td>
            
            
            
           
            <?php if($d[estadoev]=='0'){ ?>
         
             <td>
            
            
            <a class="button small red" onclick="if (confirm('¿Desea eliminar este registro?')) { document.location = this.href; } return false;" href="<?php echo $this->url(array('controller' => 'Libro',
                       'action' => 'pruebaeliminar', 'id'=>$d[idEvaluacion]), 'default', true); ?>"><i class="icon-minus-sign"></i> Eliminar</a>
            
            
            </td>
            <?php }else{ ?>
            
            
            <td>
           
            
            <a class="button small gray" disabled="disabled"><i class="icon-minus-sign"></i> Eliminar</a>
            
            
            </td>
            <?php } ?>
        
        </tr>
<!--    fin del for-->
<?php endforeach; }?>
       
</table> 
        </div>  
  <?php } ?>