<link rel="stylesheet" href="<?php echo $this->baseUrl; ?>/css/jquery.datetimepicker.css" type="text/css">
<link rel="stylesheet" href="<?php echo $this->baseUrl; ?>/calendario/css/jquery.ui.all.css" type="text/css">
<link rel="stylesheet" href="<?php echo $this->baseUrl; ?>/font-awesome/font-awesome.css" type="text/css">

<script type="text/javascript" src="<?php echo $this->baseUrl; ?>/calendario/jquery.ui.core.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl; ?>/calendario/jquery.ui.widget.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl; ?>/calendario/jquery.ui.datepicker.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl; ?>/javascript/jquery.datetimepicker.js"></script>
<script>
    $(document).ready(function () {


        function noSunday(date) {
            var day = date.getDay();
            return [(day > 0), ''];
        }

        <?php  $periodo = new Zend_Session_Namespace('nombreperiodo');
        $idperiodo = $periodo->nombreperiodo;?>
        var ano =<?php echo $idperiodo?>;


        var fechain = '01-03-' + ano;
        var fechate = '31-12-' + ano;


        $("#fechaRetiro").datepicker({

            minDate: fechain,
            maxDate: fechate,
            beforeShowDay: noSunday,
            numberOfMonths: 3,


            dayNames: ['Domingo', 'Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado'],
            dayNamesMin: ['Dom', 'Lun', 'Mar', 'Mie', 'Jue', 'Vie', 'Sab'],
            firstDay: 1,
            monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
            monthNamesShort: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'],
            dateFormat: 'dd-mm-yy',
            changeMonth: true
        });




    });


</script>

<style>
    #imagePreview {
        width: 90px;
        height: 80px;
        background-position: center center;
        background-size: cover;
        -webkit-box-shadow: 0 0 1px 1px rgba(0, 0, 0, .3);
        display: inline-block;
        margin-left: 20px;
    }

    .buscador {
        padding: 5px;
        width: 595px;
    }

    p#texto {
        text-align: center;
        color: white;
        padding-top: 4px;

    }

    div#div_file {
        position: relative;
        margin-left: 45px;
        height: 25px;
        width: 70px;
        background-color: #2499e3;

    }

    input#foto {
        position: absolute;
        top: 0px;
        left: 0px;
        right: 0px;
        bottom: 0px;
        width: 100%;
        height: 100%;
        opacity: 0;
    }

    input, select {
        margin-top: 3px;
        margin-bottom: 3px;
        display: inline-block;
        *display: inline; /* for IE7*/
        zoom: 1; /* for IE7*/
        vertical-align: middle;
        margin-left: 20px;
        max-width: 40%;
    }

    .chzn-container {
        margin-top: 3px;
        margin-bottom: 3px;
        display: inline-block;
        *display: inline; /* for IE7*/
        zoom: 1; /* for IE7*/
        vertical-align: middle;
        margin-left: 20px;
        max-width: 40%;
    }

    label {
        display: inline-block;
        *display: inline; /* for IE7*/
        zoom: 1; /* for IE7*/
        padding-top: 3px;
        text-align: right;
        width: 120px;
    }

    input[type="checkbox"] + label {
        display: inline-block;
        *display: inline; /* for IE7*/
        zoom: 1; /* for IE7*/
        padding-top: 3px;
        text-align: right;
        width: 120px;
    }

    .botones {
        position: absolute;
        margin-left: auto;
        margin-right: auto;
        left: 0;
        right: 0;
    }

    .tab-content {
        height: 120px;
        max-height: 140px;
    }

    h5 {
        margin: 0 0 10px 0;
    }


</style>
<?php
$form = $this->form;
?>

<form id="formElem" name="formElem" enctype="application/x-www-form-urlencoded" action="" method="post">



    <div class="col_12 column center" id="matricula">
        <div style="width: 100%;display: inline-flex;">

            <div class="col_10 aligned_form" style="border: 1px solid #efefef;">
                <div class="col_10" style="text-align: center;display: inline;">

                    <div>
                        <h5>
                            <?php
                            echo $this->alumno;
                            ?>
                        </h5>

                    </div>
                    <div>
                        <?php
                        echo $form->fechaRetiro->renderLabel() . $form->fechaRetiro->renderViewHelper();
                        ?>
                    </div>
                    <div>
                        <?php
                        echo $form->motivo->renderLabel() . $form->motivo->renderViewHelper();
                        ?>
                    </div>
                    <div>
                        <?php
                        echo $form->idAlumnosActual->renderLabel() . $form->idAlumnosActual->renderViewHelper();
                        ?>
                    </div>


                </div>


            </div>
        </div>



        <div class="col_12 center">
            <div>
                <?php
                echo  $form->submit->renderViewHelper().' '.$form->join->renderViewHelper();
                ?>
            </div>


        </div>
    </div>

</form>




