<script type="text/javascript">
    $(function(){
       $('#item_region').change(function(){
           
       
            $('#item_provincia').html('');
             $('#item_comuna').html('');
       
          var ajax = $.ajax({
             type: "GET",
             url: "../../getprovincia/id/" + $(this).val(),
             async: true,
             dataType: "json",
             beforeSend: function(x) {
                if(x && x.overrideMimeType) {
                   x.overrideMimeType("application/j-son;charset=UTF-8");
                }
             },
             success: function(data){
                var options = '';
                   for (var i = 0; i < data.length; i++) {
                      options += '<option value="' + data[i].idProvincia + '">' + data[i].nombreProvincia + '</option>';
                   }
                   $('#item_provincia').html(options);
             }
        });
      });
      $('#item_provincia').change(function(){
          $('#item_comuna').html('');
          var ajax = $.ajax({
             type: "GET",
             url: "../../getcomuna/id/" + $(this).val(),
             async: true,
             dataType: "json",
             beforeSend: function(x) {
                if(x && x.overrideMimeType) {
                   x.overrideMimeType("application/j-son;charset=UTF-8");
                }
             },
             success: function(data){
                var options = '';
                   for (var i = 0; i < data.length; i++) {
                      options += '<option value="' + data[i].idComuna + '">' + data[i].nombreComuna + '</option>';
                   }
                   $('#item_comuna').html(options);
             }
        });
      });
    });
 </script>

<?php echo $this->form;