<script src="<?php echo $this->baseUrl; ?>/javascript/buscador.js"></script>
<style>

    input[type="text"] {
        padding: 5px;
        width: 595px;
    }
</style>
<div id="divTabla" style="margin-top: 20px;">
                    <label for="txtBuscar">Buscar: </label>
                    <input type="text" id="txtBuscar" autofocus
                           placeholder="Escriba el texto que desea encontrar y presione ENTER">
    <table id="tblTabla" class="striped sortable" style="margin-top: 10px">
        <thead>
        <tr>

            <th>Enseñanza</th>
            <th>Grado</th>
            <th>Letra</th>
            <th>Establecimiento</th>
            <th>Generar</th>

        </tr>
        </thead>
        <?php
        $cargo = new Zend_Session_Namespace('cargo');
        $rol = $cargo->cargo;

        $ingreson = new Zend_Session_Namespace('ingresonota');
        $ingresonota = $ingreson->ingresonota;
        $datos = $this->datos;

        if (!empty($datos)) {?>
            <?php foreach ($this->datos as $d) : ?>

                <tr>

                    <td><?php echo $d['nombreTipoEnsenanza']; ?></td>

                    <td><?php echo $d['nombreGrado']; ?></td>

                    <td><?php echo $d['letra']; ?></td>

                    <td><?php echo $d['nombreEstablecimiento']; ?></td>

                    <td>

                        <div class="ventana"><a class="button small blue" href="<?php echo $this->url(array('controller' => 'Informes',
                                'action' => 'planilla', 'id' => $d['idCursos']), 'default', true); ?>"><i class="icon-hand-up"></i> Generar</a></div>
                    </td>

                </tr>

            <?php endforeach;
        }
        ?>

    </table>
