
<a class="button medium blue" href="<?php echo $this->url(array('controller' => 'Informes',
    'action' => 'informenotas'),'default',TRUE); ?>"><span class="icon book small" data-icon="j"></span>Informe Notas</a>


    <a class="button medium blue" href="<?php echo $this->url(array('controller' => 'Informes',
    'action' => 'certificadoalumno'),'default',TRUE); ?>"><span class="icon book small" data-icon="j"></span>Certificado Alumnos</a>

    <a class="button medium blue" href="<?php echo $this->url(array('controller' => 'Informes',
    'action' => 'personalidad'),'default',TRUE); ?>"><span class="icon book small" data-icon="j"></span>Informe Personalidad</a>

    <a class="button medium blue" href="<?php echo $this->url(array('controller' => 'Informes',
    'action' => 'matriculas'),'default',TRUE); ?>"><span class="icon book small" data-icon="j"></span>Certificado Matrículas</a>
