<div class="pagination" style="width:100%">
    <div style="float:left;width:28%">
    </div>

 
    <div style="float:right;width:70%;">

        <?php if (isset($this->previous)): ?>
              <a href="<?= $this->url(array('page' => $this->first)); ?>">Inicio</a> |
        <?php else: ?>
                <span class="disabled">Inicio</span> |
        <?php endif; ?>

        <?php if (isset($this->previous)): ?>
              <a href="<?= $this->url(array('page' => $this->previous)); ?>">&lt; Anterior</a> |
        <?php else: ?>
            <span class="disabled">&lt; Anterior</span> |
        <?php endif; ?>

        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <a href="<?= $this->url(array('page' => $page)); ?>"><?= $page; ?></a>
            <?php else: ?>
                <?= $page; ?>
            <?php endif; ?>
        <?php endforeach; ?>

        <?php if (isset($this->next)): ?>
              | <a href="<?= $this->url(array('page' => $this->next)); ?>">Siguiente &gt;</a> |
        <?php else: ?>
            | <span class="disabled">Siguiente &gt;</span> |
        <?php endif; ?>

        <?php if (isset($this->next)): ?>
              <a href="<?= $this->url(array('page' => $this->last)); ?>">Última</a>
        <?php else: ?>
            <span class="disabled">Última</span>
        <?php endif; ?>
        &nbsp; Página <?= $this->current; ?> de <?= $this->last; ?>
    </div>
 </div>