
<style>
  
                .unavailable span {
 color: green !important; //muestra rojos los festivos
 background-color: blue;
}
             .unavailable{
 background-color: blue;
}
</style>
<a class="button medium blue" href="<?php echo $this->url(array('controller' => 'Sige',
    'action' => 'asistencia'), null, TRUE);
?>"><i class="icon-hand-left"></i> Volver</a>

<div id="informacion"></div>

<?php echo $this->form; ?>
<script src="<?php echo $this->baseUrl; ?>/javascript/asistenciasige.js"></script>

 <div id="asistencia"></div>