<script src="<?php echo $this->baseUrl; ?>/javascript/buscador.js"></script>

<style>
    #divInfo {
        text-align: center;
        padding-bottom: 10px;
        margin-bottom: 40px;
    }

    #divTabla {

    }

    input[type="text"] {
        padding: 5px;
        width: 595px;
    }

</style>


<?php
$nombrecurso = new Zend_Session_Namespace('nombre_curso');
$nombre_curso = $nombrecurso->nombre_curso;

$idcurso = new Zend_Session_Namespace('id_curso');
$id_curso = $idcurso->id_curso;

$iddetallecurso = new Zend_Session_Namespace('id_detalle_curso');
$id_detalle_curso = $iddetallecurso->id_detalle_curso;

$roles = new Zend_Session_Namespace('cargo');
$rol = $roles->cargo;

$ingreson = new Zend_Session_Namespace('ingresonota');
$ingresonota = $ingreson->ingresonota;

?>
<?php if ($rol == '1' || $rol == '5' || $rol == '3') { ?>
    <a class="button medium blue" href="<?php echo $this->url(array('controller' => 'Sige',
        'action' => 'agregarasistencia'), null, TRUE);
    ?>"> <i class="icon-plus"></i> Agregar Asistencia</a>

<?php } ?>

<a class="button medium blue" href="<?php echo $this->url(array('controller' => 'Sige',
    'action' => 'index'), null, TRUE);
?>"><i class="icon-hand-left"></i> Volver</a>


<div id="divTabla" style="margin-top: 20px;">
                    <label for="txtBuscar">
        <i class="icon-search"></i> Buscar: </label>
                    <input type="text" id="txtBuscar" autofocus
                           placeholder="Escriba el texto que desea encontrar y presione ENTER">

    <table id="tblTabla" class="striped sortable" style="margin-top: 10px">
        <thead>
        <tr>
            <th>Establecimiento</th>
            <th>Grado</th>
            <th>Letra</th>
            <th style="width: 100px;">Fecha</th>
            <th>Ver Asistencia</th>
            <?php if ($rol == '1' || $rol == '5' || $rol == '3') { ?>
                <th>Editar</th>

            <?php } ?>
            <th>Enviar</th>
            <th>Código Asistencia</th>
            <th>Consulta Reporte Asistencia</th>
            <th>Estado Reporte Asistencia</th>
            <th>Ver Historial</th>
            <th>Ver Historial Consulta</th>
        </tr>
        </thead>
        <?php
        $var0 = $this->paginator;
        if (!empty($var0)) {
            foreach ($this->paginator as $c) : ?>
                <tr>
                    <td><?php echo $c['nombreEstablecimiento']; ?></td>

                    <td><?php echo $c['nombreGrado']; ?></td>

                    <td><?php echo $c['letra']; ?></td>
                    <td>
                        <?php echo date("d-m-Y", strtotime($c['fechaAsistencia']));
                        ?>
                    </td>
                    <td>
                        <div class="ventana">
                            <a class="button small blue" href="<?php
                            echo $this->url(array(
                                'controller' => 'Sige',
                                'action' => 'verasistencia',
                                'id' => base64_encode($c['idAsistencia'])
                            ), 'default', true);
                            ?>"><i class="icon-eye-open"></i> Ver Asistencia
                            </a>
                        </div>
                    </td>
                    <?php if ($rol == '1' || $rol == '5' || $rol == '3') { ?>
                        <td>
                            <a class="button small green" href="<?php echo $this->url(array('controller' => 'Sige',
                                'action' => 'editarasistencia', 'id' => base64_encode($c['idAsistencia'])), 'default', true); ?>"><i
                                        class="icon-edit"></i> Editar</a>


                        </td>


                    <?php } ?>
                    <td>
                        <?php
                        $params = implode("','", [
                            $c['idEstablecimiento'],
                            $c['idPeriodo'],
                            $c['nombrePeriodo'],
                            $c['idAsistencia'],
                            $c['idCursos']
                        ]);
                        ?>

                        <a class="button small red" onclick="enviarasistencia('<?= $params ?>'); return false;"><i
                                    class="icon-upload"></i> Enviar
                        </a>
                    </td>
                    <td><?php

                        if (empty($c['Codigos'][0]['codigoasistencia'])) {
                            echo 'Sin código';
                        } else {
                            echo $c['Codigos'][0]['codigoasistencia'];
                        }
                        ?></td>

                    <td>
                        <?php
                        $parametros = implode("','", [
                            $c['idEstablecimiento'],
                            $c['idPeriodo'],
                            $c['Codigos'][0]['codigoasistencia'],
                            $c['idCursos'],
                            $c['idAsistencia'],
                            $c['Codigos'][0]['idCodigoAsistencia']
                        ]);
                        ?>

                        <a class="button small blue" onclick="reporteasistencia('<?= $parametros ?>'); return false;"><i
                                    class="icon-upload"></i> Consultar
                        </a>
                    </td>
                    <td>
                        <?php
                        if (empty($c['Codigos'][0]['estadoasistencia'])) {
                            echo 'Sin Estado';
                        } else {

                            switch ($c['Codigos'][0]['estadoasistencia']) {
                                case 1:
                                    echo $c['Codigos'][0]['estadoasistencia'] . ' Asistencia procesada exitosamente.';
                                    break;
                                case 2:
                                    echo $c['Codigos'][0]['estadoasistencia'] . ' Asistencia procesada con Observaciones.';
                                    break;
                                case 3:
                                    echo $c['Codigos'][0]['estadoasistencia'] . ' Asistencia procesada con Errores.';
                                    break;
                                case 4:
                                    echo $c['Codigos'][0]['estadoasistencia'] . ' Asistencia aún no ha sido procesada.';
                                    break;
                                case 5:
                                    echo $c['Codigos'][0]['estadoasistencia'] . ' Parámetros no corresponden';
                                    break;
                                case 6:
                                    echo $c['Codigos'][0]['estadoasistencia'] . ' RBD NO tiene servicio disponible.';
                                    break;
                                case 7:
                                    echo $c['Codigos'][0]['estadoasistencia'] . ' Convenio NO tiene asociado el RBD.';
                                    break;
                                case 8:
                                    echo $c['Codigos'][0]['estadoasistencia'] . ' Servicio NO disponible.';
                                    break;
                                case 9:
                                    echo $c['Codigos'][0]['estadoasistencia'] . ' Semilla de operación NO válida o ha caducado (renovar semilla)';
                                    break;
                                case 10:
                                    echo $c['Codigos'][0]['estadoasistencia'] . ' Error interno del servicio.';
                                    break;
                            }
                        }
                        ?>
                    </td>
                    <td>
                        <div class="ventana">
                            <a class="button small blue" href="<?php echo $this->url(array('controller' => 'Sige',
                                'action' => 'verhistorialasistencia', 'id' => $c['idAsistencia']), 'default', true); ?>"><i
                                        class="icon-eye-open"></i> Ver Historial</a>

                        </div>
                    </td>

                    <td>
                        <div class="ventana">
                            <a class="button small blue" href="<?php echo $this->url(array('controller' => 'Sige',
                                'action' => 'verhistorialasistenciareporte', 'id' => $c['idAsistencia']), 'default', true); ?>"><i
                                        class="icon-eye-open"></i> Ver Historial Consulta</a>

                        </div>
                    </td>

                </tr>
                <?php
            endforeach;
        }
        ?>
    </table>
    <?= $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
</div>

<script type="text/javascript">
    var enviarasistencia = function (est, periodo, nombreperiodo, idasistencia, idcurso) {
        if (est != '' && periodo != '' && nombreperiodo != '' && idcurso != '' && idasistencia != '') {
            $.ajax({
                cache: false,
                async: true,
                dataType: 'json',
                type: 'POST',
                contentType: 'application/x-www-form-urlencoded',
                url: '../Sige/enviaasistencia/',
                data: JSON.stringify({
                    est: est,
                    periodo: periodo,
                    nombreperiodo: nombreperiodo,
                    idasistencia: idasistencia,
                    idcurso: idcurso
                }),
                beforeSend: function (data) {
                    $('#div_cliente').html('<label>Validando...</label>');
                },
                success: function (data) {
                    if (parseInt(data.response) === 1) {
                        switch (parseInt(data.status)) {
                            case 1:
                                alert('Operación/Acción ejecutada exitosamente.');
                                location.reload();
                                break;
                            case 2:
                                alert('Error(es) de validación(es) de Negocio.');
                                location.reload();
                                break;
                            case 3:
                                alert('RBD NO tiene servicio disponible.');
                                location.reload();
                                break;
                            case 4:
                                alert('Convenio NO tiene asociado el RBD.');
                                location.reload();
                                break;
                            case 5:
                                alert('Servicio NO disponible.');
                                location.reload();
                                break;
                            case 6:
                                alert('Semilla de operación NO válida o ha caducado (renovar semilla)');
                                location.reload();
                                break;
                            case 7:
                                alert('Error interno de servicio.');
                                location.reload();
                                break;


                        }
                    } else if (parseInt(data.response) === 0) {
                        alert('Error Con el envío 1');
                    } else {
                        alert('Error Con el envío 2');
                    }
                },
                error: function () {
                    alert('Error Con el envío 3');
                }
            });
        } else {
            alert('No se Puede Consultar Existen datos Vacíos');
        }
    }


    var reporteasistencia = function (est, periodo, codigo, idcurso, idasistencia, idcodigo) {
        if (est != '' && periodo != '' && codigo != '' && idcurso != '' && idasistencia != '' && idcodigo != '') {

            $.ajax({
                cache: false,
                async: true,
                dataType: 'json',
                type: 'POST',
                contentType: 'application/x-www-form-urlencoded',
                url: '../Sige/reporteasistencia/',
                data: JSON.stringify({
                    est: est,
                    periodo: periodo,
                    codigo: codigo,
                    idcurso: idcurso,
                    idasistencia: idasistencia,
                    idcodigo: idcodigo
                }),
                beforeSend: function (data) {
                    $('#div_cliente').html('<label>Validando...</label>');
                },
                success: function (data) {
                    if (parseInt(data.response) === 1) {
                        switch (parseInt(data.status)) {
                            case 1:
                                alert('Asistencia procesada exitosamente.');
                                location.reload();
                                break;
                            case 2:
                                alert('Asistencia procesada con Observaciones.');
                                location.reload();
                                break;
                            case 3:
                                alert('Asistencia procesada con Errores.');
                                location.reload();
                                break;
                            case 4:
                                alert('Asistencia aún no ha sido procesada.');
                                location.reload();
                                break;
                            case 5:
                                alert('Parámetros no corresponden.');
                                location.reload();
                                break;
                            case 6:
                                alert('RBD NO tiene servicio disponible.');
                                location.reload();
                                break;
                            case 7:
                                alert('Convenio NO tiene asociado el RBD.');
                                location.reload();
                                break;
                            case 8:
                                alert('Servicio NO disponible.');
                                location.reload();
                                break;
                            case 9:
                                alert('Semilla de operación NO válida o ha caducado (renovar semilla).');
                                location.reload();
                                break;
                            case 10:
                                alert('Error interno del servicio.');
                                location.reload();
                                break;


                        }
                    } else if (parseInt(data.response) === 0) {
                        alert('Error Con el envío 1');
                    } else {
                        alert('Error Con el envío 2');
                    }
                },
                error: function () {
                    alert('Error Con el envío 3');
                }
            });
        } else {
            alert('No se Puede Consultar Existen datos Vacíos');
        }
    }
</script>