<!doctype html>
<html>
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
</head>
<body>
<div class="lg:flex justify-center ">
    <div class="lg:w-1/2 xl:max-w-screen-sm">

        <div class="mt-12 px-10 sm:px-24 md:px-48 lg:px-12 lg:mt-16 xl:px-24 xl:max-w-2xl">
            <h2 class="text-center text-4xl font-display font-semibold lg:text-left xl:text-5xl
                    xl:text-bold">Ingreso al Sistema</h2>
            <div class="mt-12">
                <form name="inicio" method='post' action='<?=$this->escape($this->action);?>'>
                    <div class="mt-6">
                        <div class="text-sm font-bold text-gray-700 tracking-wide">Rut Usuario</div>
                        <input type="text" id="user" name='username' class="w-full text-lg py-2 border-b border-gray-300 focus:outline-none focus:border-blue-500" type="" placeholder="Rut Usuario"/>

                    </div>
                    <div class="mt-6">
                        <div class="flex justify-between items-center">
                            <div class="text-sm font-bold text-gray-700 tracking-wide">
                                Contraseña
                            </div>
                        </div>
                        <input type="password" name='password' class="w-full text-lg py-2 border-b border-gray-300 focus:outline-none focus:border-blue-500" placeholder="Contrase&ntilde;a">
                    </div>
                    <div class="mt-6">
                        <div class="flex justify-between items-center">
                            <div class="text-sm font-bold text-gray-700 tracking-wide">
                                Periodo
                            </div>
                        </div>
                        <select class="w-full text-lg py-2 border-b border-gray-300 focus:outline-none focus:border-blue-500" id="periodo" name='periodo' placeholder="Periodo">
                            <?php foreach ($this->dato as $d) : ?>
                                <option value="<?php echo $d->idPeriodo;?>"><?php echo $d->nombrePeriodo;?></option>
                            <?php endforeach; ?>
                        </select>
                   </div>
                    <div class="mt-10">
                        <button class="bg-blue-400 text-gray-100 p-4 w-full tracking-wide
                                font-semibold font-display focus:outline-none focus:shadow-outline hover:bg-blue-600
                                shadow-lg" style="background-color: #1d6dc1">
                            Entrar
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
</body>
</html>
