<script src="<?php echo $this->baseUrl; ?>/javascript/cuentasperiodo.js"></script>
<style>
    ul {
        list-style-type: none;
    }

    li {
        padding: 1px 0;
    }


    input[type="radio"], input[type="checkbox"] {
        margin: -4px 0 0 0;
    }

    i {
        color: #388ED1;
        cursor: pointer;
        margin: 1px 0 0 0;
        position: relative;
        top: 1px;
    }

    ul > li > div {
        display: none;
    }
</style>


<?php echo $this->form; ?>

<div id="asignatura" style="margin-top: 20px; border-top:1px solid #1D6DC1;;"></div>


