<link href="<?php echo $this->baseUrl; ?>/css/bootstrap-3.3.7-dist/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<link href="<?php echo $this->baseUrl; ?>/css/estilomensajes.css" rel="stylesheet">


<link rel='stylesheet prefetch' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css'>
<div class="mail-box">
    <aside class="sm-side">
        <div class="inbox-body">
            <?php if (!$this->messagesnuevo) { ?>
                <a href="<?php echo $this->url(array('controller' => 'mensaje',
                    'action' => 'nuevo'), 'default', TRUE); ?>" data-toggle="modal" title="Compose" class="btn btn-compose">
                    Nuevo Mensaje
                </a>
            <?php } ?>

        </div>
        <ul class="inbox-nav inbox-divider">
            <li class="active">
                <a href="<?php echo $this->url(array('controller' => 'mensaje',
                    'action' => 'entrada'), 'default', TRUE); ?>"><i class="fa fa-inbox"></i> Entrada <span class="label label-danger pull-right"><?php if($this->totalnoleido>0){echo $this->totalnoleido;} ?></span></a>

            </li>
            <li>
                <a href="<?php echo $this->url(array('controller' => 'mensaje',
                    'action' => 'enviado'), 'default', TRUE); ?>"><i class="fa fa-envelope-o"></i> Enviados</a>
            </li>
        </ul>


    </aside>
    <aside class="lg-side">
        <div class="inbox-head">
            <?php if (!$this->validaresp) { ?>

            <h5><a href="<?php echo $this->url(array('controller' => 'Mensaje',
                    'action' => 'responder', 'id' => $this->datos[0]['idMensaje'])); ?>" class="btnrep"><i class="icon-reply icon-1x"></i> Responder</a></h5>

            <?php } ?>

            <h3><?php if ($this->messages){echo 'Error';}else{echo $this->datos[0]['asunto'];}  ?></h3>

            <h5><?php if ($this->messages){echo 'Error';}else{echo 'De: '.$this->datos[0]['nombrescuenta'].' '.$this->datos[0]['paternocuenta'].' '.$this->datos[0]['maternocuenta'];}  ?>
                <span class="mailbox-read-time pull-right"><?php if ($this->messages){echo 'Error';}else{echo strtoupper($this->datos[0]['fechaformato']);}  ?></span></h5>



        </div>





        <div class="inbox-body">
            <div class="mailbox-read-message">
                <?php if ($this->messages): ?>
                    <div class="t_a_message">
                        <ul>
                            <?php foreach ($this->messages as $msg): ?>
                                <li><?php echo $msg; ?></li>
                            <?php endforeach;?>
                        </ul>
                    </div>
                <?php endif;?>
                <?php echo $this->datos[0]['mensaje'];  ?>
            </div>
        </div>
    </aside>
</div>


