<link href="<?php echo $this->baseUrl; ?>/css/bootstrap-3.3.7-dist/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<link href="<?php echo $this->baseUrl; ?>/css/estilomensajes.css" rel="stylesheet">
<link rel='stylesheet prefetch' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css'>
<script src="https://code.jquery.com/jquery-1.9.1.js"></script>
<script src="<?php echo $this->baseUrl; ?>/css/bootstrap-3.3.7-dist/js/bootstrap.js"></script>
<script src="<?php echo $this->baseUrl; ?>/css/bootstrap-3.3.7-dist/plugins/iCheck/icheck.min.js"></script>
<link rel="stylesheet" href="<?php echo $this->baseUrl; ?>/css/bootstrap-3.3.7-dist/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">
<script src="<?php echo $this->baseUrl; ?>/css/bootstrap-3.3.7-dist/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
<script src="<?php echo $this->baseUrl; ?>/css/bootstrap-3.3.7-dist/plugins/bootstrap-wysihtml5/locales/bootstrap-wysihtml5.es-ES.js"></script>
<script src="<?php echo $this->baseUrl; ?>/javascript/chosen_v1.7.0/chosen.jquery.js" type="text/javascript"></script>
<link rel="stylesheet" href="<?php echo $this->baseUrl; ?>/javascript/chosen_v1.7.0/chosen.css">
<?php
$periodo = new Zend_Session_Namespace('nombreperiodo');
$nombreperiodo = $periodo->nombreperiodo;
$form = $this->form;
$cargo = new Zend_Session_Namespace('cargo');
$rol = $cargo->cargo;
?>
<div class="mail-box">
    <aside class="sm-side">
        <div class="inbox-body">
            <?php if (!$this->messagesnuevo) { ?>
                <a href="<?php echo $this->url(array('controller' => 'mensaje',
                    'action' => 'nuevo'), 'default', TRUE); ?>" data-toggle="modal" title="Compose" class="btn btn-compose">
                    Nuevo Mensaje
                </a>
            <?php } ?>

        </div>
        <ul class="inbox-nav inbox-divider">
            <li>
                <a href="<?php echo $this->url(array('controller' => 'mensaje',
                    'action' => 'entrada'), 'default', TRUE); ?>"><i class="fa fa-inbox"></i> Entrada <span
                            class="label label-danger pull-right"><?php if ($this->totalnoleido > 0) {
                            echo $this->totalnoleido;
                        } ?></span></a>

            </li>
            <li>
                <a href="<?php echo $this->url(array('controller' => 'mensaje',
                    'action' => 'enviado'), 'default', TRUE); ?>"><i class="fa fa-envelope-o"></i> Enviados</a>
            </li>
        </ul>
    </aside>
    <aside class="lg-side">

        <div class="inbox-head">
            <?php if (!$this->validaresp) { ?>
            <h3>Responder</h3>
            <?php } ?>

        </div>
        <div class="inbox-body">

            <div class="col-md-9">
                <div class="box box-primary">
                    <?php if ($this->validaresp) { ?>
                        <div class="error">
                            <ul>
                                <?php foreach ($this->validaresp as $msg) : ?>
                                    <li><?php echo $msg; ?></li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    <?php }else{ ?>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <form id="formElem" name="formElem" enctype="application/x-www-form-urlencoded" action method="post">

                            <div class="form-group">
                                <?php echo $form->para->renderViewHelper(); ?>
                            </div>
                            <div class="form-group">
                                <?php echo $form->asunto->renderViewHelper(); ?>
                            </div>
                            <div class="form-group">
                                <?php echo $form->mensaje->renderViewHelper(); ?>
                            </div>

                            <div class="form-group">
                                <?php echo $form->submit->renderViewHelper(); ?>

                            </div>

                        </form>
                    </div>
                    <?php } ?>
                </div>
            </div>
        </div>
    </aside>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('#compose-textarea').wysihtml5({
            locale: 'es-ES',
            toolbar: {
                "font-styles": true, //Font styling, e.g. h1, h2, etc. Default true
                "emphasis": true, //Italics, bold, etc. Default true
                "lists": true, //(Un)ordered lists, e.g. Bullets, Numbers. Default true
                "html": false, //Button which allows you to edit the generated HTML. Default false
                "link": false, //Button to insert a link. Default true
                "image": false, //Button to insert an image. Default true,
                "color": false, //Button to change color of font
                "blockquote": true, //Blockquote
                "fa": false
            }
        });
    })
    ;

</script>
