<script type="text/javascript">
    $(function () {
        $('#idCodigoTipo').change(function (e) {

            $('#idcurso').html('');

            $.ajax({
                type: "GET",
                url: "getnivel/id/" + $(this).val(),
                async: true,
                dataType: "json",
                beforeSend: function (x) {
                    if (x && x.overrideMimeType) {
                        x.overrideMimeType("application/j-son;charset=UTF-8");
                    }
                },
                success: function (data) {
                    var options = '';
                    for (var i = 0; i < data.length; i++) {
                        options += '<option value="' + data[i].idCodigoGrado + '">(' + data[i].idGrado + ') ' + data[i].nombreGrado + '</option>';
                    }
                    $('#nivel').html(options);
                }
            });
            e.stopImmediatePropagation();
        });

        $('#codigoSector').change(function (e) {

            $('#CodigoEspecialidad').html('');

            $.ajax({
                type: "GET",
                url: "getespecialidad/id/" + $(this).val(),
                async: true,
                dataType: "json",
                beforeSend: function (x) {
                    if (x && x.overrideMimeType) {
                        x.overrideMimeType("application/j-son;charset=UTF-8");
                    }
                },
                success: function (data) {
                    var options = '';
                    for (var i = 0; i < data.length; i++) {
                        options += '<option value="' + data[i].idCodigoEspecialidad + '">(' + data[i].idCodigoEspecialidad + ') ' + data[i].nombreEspecialidad + '</option>';
                    }
                    $('#codigoEspecialidad').html(options);
                }
            });
            e.stopImmediatePropagation();
        });
    });

</script>

<?php echo $this->form; ?>
