<!-- jQuery -->
<script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
        integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
        crossorigin="anonymous"></script>


<!-- BS JavaScript -->
<script src="<?php echo $this->baseUrl; ?>/bootstrap-4.0.0/dist/js/bootstrap.min.js"></script>

<a class="button blue" href="<?php echo $this->url(array('controller' => 'Cursos',
    'action' => 'horario', 'id' => $this->datocurso,'idt'=>'1'), 'default', true); ?>">Horario Mañana</a>
<a class="button blue" href="<?php echo $this->url(array('controller' => 'Cursos',
    'action' => 'horario', 'id' => $this->datocurso,'idt'=>'2'), 'default', true); ?>">Horario Tarde</a>

<h4>Curso: <?php echo $this->nombrecurso; ?></h4>


<h2><?php echo $this->title; ?></h2>
<?php $form = $this->dato; ?>
<div style="width:100%;">
    <style scoped>
        h3 {
            orphans: 3;
            widows: 3;
        }

        h2,
        h3 {
            page-break-after: avoid;
        }

        h1, h2, h3, h4, h5, h6 {
            margin-top: 0;
            margin-bottom: 0.5rem;
        }

        h1, h2, h3, h4, h5, h6,
        .h1, .h2, .h3, .h4, .h5, .h6 {
            margin-bottom: 0.5rem;
            font-family: inherit;
            font-weight: 500;
            line-height: 1.2;
            color: inherit;
        }

        h3, .h3 {
            font-size: 1.75rem;
        }

        .popover {
            position: absolute;
            top: 0;
            left: 0;
            z-index: 1060;
            display: block;
            max-width: 276px;
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
            font-style: normal;
            font-weight: 400;
            line-height: 1.5;
            text-align: left;
            text-align: start;
            text-decoration: none;
            text-shadow: none;
            text-transform: none;
            letter-spacing: normal;
            word-break: normal;
            word-spacing: normal;
            white-space: normal;
            line-break: auto;
            font-size: 0.875rem;
            word-wrap: break-word;
            background-color: #fff;
            background-clip: padding-box;
            border: 1px solid rgba(0, 0, 0, 0.2);
            border-radius: 0.3rem;
        }

        .popover .arrow {
            position: absolute;
            display: block;
            width: 1rem;
            height: 0.5rem;
            margin: 0 0.3rem;
        }

        .popover .arrow::before, .popover .arrow::after {
            position: absolute;
            display: block;
            content: "";
            border-color: transparent;
            border-style: solid;
        }

        .bs-popover-top, .bs-popover-auto[x-placement^="top"] {
            margin-bottom: 0.5rem;
        }

        .bs-popover-top .arrow, .bs-popover-auto[x-placement^="top"] .arrow {
            bottom: calc((0.5rem + 1px) * -1);
        }

        .bs-popover-top .arrow::before, .bs-popover-auto[x-placement^="top"] .arrow::before,
        .bs-popover-top .arrow::after, .bs-popover-auto[x-placement^="top"] .arrow::after {
            border-width: 0.5rem 0.5rem 0;
        }

        .bs-popover-top .arrow::before, .bs-popover-auto[x-placement^="top"] .arrow::before {
            bottom: 0;
            border-top-color: rgba(0, 0, 0, 0.25);
        }

        .bs-popover-top .arrow::after, .bs-popover-auto[x-placement^="top"] .arrow::after {
            bottom: 1px;
            border-top-color: #fff;
        }

        .bs-popover-right, .bs-popover-auto[x-placement^="right"] {
            margin-left: 0.5rem;
        }

        .bs-popover-right .arrow, .bs-popover-auto[x-placement^="right"] .arrow {
            left: calc((0.5rem + 1px) * -1);
            width: 0.5rem;
            height: 1rem;
            margin: 0.3rem 0;
        }

        .bs-popover-right .arrow::before, .bs-popover-auto[x-placement^="right"] .arrow::before,
        .bs-popover-right .arrow::after, .bs-popover-auto[x-placement^="right"] .arrow::after {
            border-width: 0.5rem 0.5rem 0.5rem 0;
        }

        .bs-popover-right .arrow::before, .bs-popover-auto[x-placement^="right"] .arrow::before {
            left: 0;
            border-right-color: rgba(0, 0, 0, 0.25);
        }

        .bs-popover-right .arrow::after, .bs-popover-auto[x-placement^="right"] .arrow::after {
            left: 1px;
            border-right-color: #fff;
        }

        .bs-popover-bottom, .bs-popover-auto[x-placement^="bottom"] {
            margin-top: 0.5rem;
        }

        .bs-popover-bottom .arrow, .bs-popover-auto[x-placement^="bottom"] .arrow {
            top: calc((0.5rem + 1px) * -1);
        }

        .bs-popover-bottom .arrow::before, .bs-popover-auto[x-placement^="bottom"] .arrow::before,
        .bs-popover-bottom .arrow::after, .bs-popover-auto[x-placement^="bottom"] .arrow::after {
            border-width: 0 0.5rem 0.5rem 0.5rem;
        }

        .bs-popover-bottom .arrow::before, .bs-popover-auto[x-placement^="bottom"] .arrow::before {
            top: 0;
            border-bottom-color: rgba(0, 0, 0, 0.25);
        }

        .bs-popover-bottom .arrow::after, .bs-popover-auto[x-placement^="bottom"] .arrow::after {
            top: 1px;
            border-bottom-color: #fff;
        }

        .bs-popover-bottom .popover-header::before, .bs-popover-auto[x-placement^="bottom"] .popover-header::before {
            position: absolute;
            top: 0;
            left: 50%;
            display: block;
            width: 1rem;
            margin-left: -0.5rem;
            content: "";
            border-bottom: 1px solid #f7f7f7;
        }

        .bs-popover-left, .bs-popover-auto[x-placement^="left"] {
            margin-right: 0.5rem;
        }

        .bs-popover-left .arrow, .bs-popover-auto[x-placement^="left"] .arrow {
            right: calc((0.5rem + 1px) * -1);
            width: 0.5rem;
            height: 1rem;
            margin: 0.3rem 0;
        }

        .bs-popover-left .arrow::before, .bs-popover-auto[x-placement^="left"] .arrow::before,
        .bs-popover-left .arrow::after, .bs-popover-auto[x-placement^="left"] .arrow::after {
            border-width: 0.5rem 0 0.5rem 0.5rem;
        }

        .bs-popover-left .arrow::before, .bs-popover-auto[x-placement^="left"] .arrow::before {
            right: 0;
            border-left-color: rgba(0, 0, 0, 0.25);
        }

        .bs-popover-left .arrow::after, .bs-popover-auto[x-placement^="left"] .arrow::after {
            right: 1px;
            border-left-color: #fff;
        }

        .popover-header {
            padding: 0.5rem 0.75rem;
            margin-bottom: 0;
            font-size: 1rem;
            color: inherit;
            background-color: #f7f7f7;
            border-bottom: 1px solid #ebebeb;
            border-top-left-radius: calc(0.3rem - 1px);
            border-top-right-radius: calc(0.3rem - 1px);
        }

        .popover-header:empty {
            display: none;
        }

        .popover-body {
            padding: 0.5rem 0.75rem;
            color: #212529;
        }

        .alert {
            position: relative;
            padding: 0.75rem 1.25rem;
            margin-bottom: 1rem;
            border: 1px solid transparent;
            border-radius: 0.25rem;
        }

        .alert-heading {
            color: inherit;
        }

        .alert-link {
            font-weight: 700;
        }

        .alert-dismissible {
            padding-right: 4rem;
        }

        .alert-dismissible .close {
            position: absolute;
            top: 0;
            right: 0;
            padding: 0.75rem 1.25rem;
            color: inherit;
        }

        .alert-primary {
            color: #004085;
            background-color: #cce5ff;
            border-color: #b8daff;
        }

        .alert-primary hr {
            border-top-color: #9fcdff;
        }

        .alert-primary .alert-link {
            color: #002752;
        }

        .alert-secondary {
            color: #383d41;
            background-color: #e2e3e5;
            border-color: #d6d8db;
        }

        .alert-secondary hr {
            border-top-color: #c8cbcf;
        }

        .alert-secondary .alert-link {
            color: #202326;
        }

        .alert-success {
            color: #155724;
            background-color: #d4edda;
            border-color: #c3e6cb;
        }

        .alert-success hr {
            border-top-color: #b1dfbb;
        }

        .alert-success .alert-link {
            color: #0b2e13;
        }

        .alert-info {
            color: #0c5460;
            background-color: #d1ecf1;
            border-color: #bee5eb;
        }

        .alert-info hr {
            border-top-color: #abdde5;
        }

        .alert-info .alert-link {
            color: #062c33;
        }

        .alert-warning {
            color: #856404;
            background-color: #fff3cd;
            border-color: #ffeeba;
        }

        .alert-warning hr {
            border-top-color: #ffe8a1;
        }

        .alert-warning .alert-link {
            color: #533f03;
        }

        .alert-danger {
            color: #721c24;
            background-color: #f8d7da;
            border-color: #f5c6cb;
        }

        .alert-danger hr {
            border-top-color: #f1b0b7;
        }

        .alert-danger .alert-link {
            color: #491217;
        }

        .alert-light {
            color: #818182;
            background-color: #fefefe;
            border-color: #fdfdfe;
        }

        .alert-light hr {
            border-top-color: #ececf6;
        }

        .alert-light .alert-link {
            color: #686868;
        }

        .alert-dark {
            color: #1b1e21;
            background-color: #d6d8d9;
            border-color: #c6c8ca;
        }

        .alert-dark hr {
            border-top-color: #b9bbbe;
        }

        .alert-dark .alert-link {
            color: #040505;
        }
    </style>

    <?php $horario = $this->horario;
    ?>

    <?php if ($this->messages) : ?>
        <div class="alert alert-danger">

            <?php foreach ($this->messages as $msg) : ?>
                <h5 class="center"><?php echo $msg; ?></h5>
            <?php endforeach; ?>

        </div>
    <?php endif; ?>


    <div class="right">
        <table>
            <tr>
                <td class="blank">Hora/Bloque</td>
                <td class="title">Lunes</td>
                <td class="title">Martes</td>
                <td class="title">Miercoles</td>
                <td class="title">Jueves</td>
                <td class="title">Viernes</td>
            </tr>

            <?php for ($i = 0; $i < count($this->bloques); $i++) { //bloque ?>
                <tr>
                    <td class="time" style="width: 5%;"><?php echo $this->bloques[$i]['nombreBloque'].'<br> '.$this->bloques[$i]['tiempoInicio'].'-'.$this->bloques[$i]['tiempoTermino']; ?></td>

                    <?php for ($j = 1; $j < 6; $j++) {//Dias
                        //Checkeamos los si poseen datos

                        for ($d = 0; $d < count($horario); $d++) {

                            if ($horario[$d]['bloque'] == $this->bloques[$i]['idBloque'] && $horario[$d]['dia'] == $j) { ?>

                                <td class="drop" style="width: 13%;" data-toggle="popover" title="Crear Bloque"
                                    data-html="true"
                                    data-content="<div>
                        <?php
                                    $form[$i][$j]->idCuenta->addMultiOption($horario[$d]['idCuenta'], $horario[$d]['nombrescuenta'].' '.$horario[$d]['paternocuenta'].' '.$horario[$d]['maternocuenta']);
                                    $form[$i][$j]->idCuenta->setValue($horario[$d]['idCuenta']);
                                    $form[$i][$j]->idHorario->setValue($horario[$d]['idHorario']);
                                    $form[$i][$j]->idAsignatura->setValue($horario[$d]['idAsignatura']);
                                    $form[$i][$j]->idCuenta->setValue($horario[$d]['idCuenta']);
                                    echo htmlentities('<form name=formElem enctype=application/x-www-form-urlencoded action method=post><input type=hidden name=bloque value=' . $this->bloques[$i]['idBloque'] . ' /><input type=hidden name=dia value=' . $j . ' />' . $form[$i][$j]->idHorario->renderViewHelper() . ' ' . $form[$i][$j]->idAsignatura->renderViewHelper() . ' ' . $form[$i][$j]->idCuenta->renderViewHelper() . ' ' . $form[$i][$j]->submit->renderViewHelper().' '.$form[$i][$j]->eliminar->renderViewHelper()); ?>
                        </form></div>">
                                    <h6><?php echo $horario[$d]['nombreAsignatura']; ?></h6>
                                    <h6><?php echo $horario[$d]['nombrescuenta'] . ' ' . $horario[$d]['paternocuenta'] . ' ' . $horario[$d]['maternocuenta']; ?></h6>
                                </td>

                                <?php $aux[$i][$j] = true; ?>

                            <?php } ?>
                        <?php } ?>

                        <?php

                        if (!$aux[$i][$j]) {
                            $form[$i][$j]->idAsignatura->setValue('');
                            $form[$i][$j]->idCuenta->setValue(''); ?>

                            <td class="drop" style="width: 13%;" data-toggle="popover" title="Crear Bloque"
                                data-html="true"
                                data-content="<div>
                        <?php echo htmlentities('<form name=formElem enctype=application/x-www-form-urlencoded action method=post><input type=hidden name=bloque value=' . $this->bloques[$i]['idBloque']  . ' /><input type=hidden name=dia value=' . $j . ' />' . $form[$i][$j]->idAsignatura->renderViewHelper() . ' ' . $form[$i][$j]->idCuenta->renderViewHelper() . ' ' . $form[$i][$j]->submit->renderViewHelper()); ?>
                        </form></div>">
                            </td>

                        <?php } ?>


                    <?php } ?>


                </tr>
            <?php } ?>
            <!--            <tr>-->
            <!--                <td class="time"></td>-->
            <!--                <td class="lunch" colspan="5">Almuerzo</td>-->
            <!--            </tr>-->


        </table>
    </div>
</div>


<style type="text/css">


    .right {
        width: 100%;
    }

    .right table {
        background: #E0ECFF;
        width: 100%;
    }

    .right td {
        background: #fafafa;
        color: #444;
        text-align: center;
        padding: 2px;
    }

    .right td {
        background: #E0ECFF;
    }

    .right td.drop {
        background: #fafafa;
        width: 100px;
        height: 40px;
        border: 1px solid #ddd;
        cursor: pointer;
    }

    .right td.over {
        background: #FBEC88;
    }

    .item {
        text-align: center;
        border: 1px solid #499B33;
        background: #fafafa;
        color: #444;
        width: 140px;
    }

    .open {
        background: blue;
    }


</style>
<script>
    // popovers Initialization
    $(function () {

        $('[data-toggle="popover"]').popover()
        $('[data-toggle="popover"]').on('click', function (e) {
            $('[data-toggle="popover"]').not(this).popover('hide');
            $('[data-toggle="popover"]').not(this).css("background", "#fafafa");


            if ($(this).prop("style")["background"] == 'blue') {
                console.log('con');
                //$(this).prop("style").removeAttribute()
                $(this).css("background", "#fafafa");
            } else {
                console.log('sin');
                $(this).css("background", "blue");
            }


            console.log($(this).find('data-content'));


            e.stopImmediatePropagation();
        });
    })
</script>



